// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.Ocr;

/// <summary>文字识别（optical_char_recognition/v1）（生成代码：1 个端点）。</summary>
public sealed class OcrService
{
    private readonly RequestPipeline _pipeline;

    internal OcrService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        Image = new OcrImageResource(pipeline);
    }

    /// <summary>Image 资源。</summary>
    public OcrImageResource Image { get; }

public sealed class OcrImageResource
{
    private readonly RequestPipeline _pipeline;

    internal OcrImageResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>识别图片中的文字（POST /open-apis/optical_char_recognition/v1/image/basic_recognize）。</summary>
    public Task<FeishuDataResponse> BasicRecognizeAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/optical_char_recognition/v1/image/basic_recognize",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

}
