// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.Vc;

/// <summary>视频会议（vc/v1 全量，机读提取）（生成代码：68 个端点）。</summary>
public sealed class VcService
{
    private readonly RequestPipeline _pipeline;

    internal VcService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        Alert = new VcAlertResource(pipeline);
        Bot = new VcBotResource(pipeline);
        Export = new VcExportResource(pipeline);
        Meeting = new VcMeetingResource(pipeline);
        MeetingRecording = new VcMeetingRecordingResource(pipeline);
        MeetingList = new VcMeetingListResource(pipeline);
        Note = new VcNoteResource(pipeline);
        ParticipantList = new VcParticipantListResource(pipeline);
        ParticipantQualityList = new VcParticipantQualityListResource(pipeline);
        Report = new VcReportResource(pipeline);
        Reserve = new VcReserveResource(pipeline);
        ReserveConfig = new VcReserveConfigResource(pipeline);
        ReserveConfigAdmin = new VcReserveConfigAdminResource(pipeline);
        ReserveConfigDisableInform = new VcReserveConfigDisableInformResource(pipeline);
        ReserveConfigForm = new VcReserveConfigFormResource(pipeline);
        ResourceReservationList = new VcResourceReservationListResource(pipeline);
        Room = new VcRoomResource(pipeline);
        RoomConfig = new VcRoomConfigResource(pipeline);
        RoomLevel = new VcRoomLevelResource(pipeline);
        ScopeConfig = new VcScopeConfigResource(pipeline);
    }

    /// <summary>Alert 资源。</summary>
    public VcAlertResource Alert { get; }
    /// <summary>Bot 资源。</summary>
    public VcBotResource Bot { get; }
    /// <summary>Export 资源。</summary>
    public VcExportResource Export { get; }
    /// <summary>Meeting 资源。</summary>
    public VcMeetingResource Meeting { get; }
    /// <summary>MeetingRecording 资源。</summary>
    public VcMeetingRecordingResource MeetingRecording { get; }
    /// <summary>MeetingList 资源。</summary>
    public VcMeetingListResource MeetingList { get; }
    /// <summary>Note 资源。</summary>
    public VcNoteResource Note { get; }
    /// <summary>ParticipantList 资源。</summary>
    public VcParticipantListResource ParticipantList { get; }
    /// <summary>ParticipantQualityList 资源。</summary>
    public VcParticipantQualityListResource ParticipantQualityList { get; }
    /// <summary>Report 资源。</summary>
    public VcReportResource Report { get; }
    /// <summary>Reserve 资源。</summary>
    public VcReserveResource Reserve { get; }
    /// <summary>ReserveConfig 资源。</summary>
    public VcReserveConfigResource ReserveConfig { get; }
    /// <summary>ReserveConfigAdmin 资源。</summary>
    public VcReserveConfigAdminResource ReserveConfigAdmin { get; }
    /// <summary>ReserveConfigDisableInform 资源。</summary>
    public VcReserveConfigDisableInformResource ReserveConfigDisableInform { get; }
    /// <summary>ReserveConfigForm 资源。</summary>
    public VcReserveConfigFormResource ReserveConfigForm { get; }
    /// <summary>ResourceReservationList 资源。</summary>
    public VcResourceReservationListResource ResourceReservationList { get; }
    /// <summary>Room 资源。</summary>
    public VcRoomResource Room { get; }
    /// <summary>RoomConfig 资源。</summary>
    public VcRoomConfigResource RoomConfig { get; }
    /// <summary>RoomLevel 资源。</summary>
    public VcRoomLevelResource RoomLevel { get; }
    /// <summary>ScopeConfig 资源。</summary>
    public VcScopeConfigResource ScopeConfig { get; }

public sealed class VcAlertResource
{
    private readonly RequestPipeline _pipeline;

    internal VcAlertResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>List /open-apis/vc/v1/alerts（Get /open-apis/vc/v1/alerts）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/vc/v1/alerts",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class VcBotResource
{
    private readonly RequestPipeline _pipeline;

    internal VcBotResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Countdown /open-apis/vc/v1/bots/countdown（Post /open-apis/vc/v1/bots/countdown）。</summary>
    public Task<FeishuDataResponse> CountdownAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/vc/v1/bots/countdown",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Events /open-apis/vc/v1/bots/events（Get /open-apis/vc/v1/bots/events）。</summary>
    public Task<FeishuDataResponse> EventsAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/vc/v1/bots/events",
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Join /open-apis/vc/v1/bots/join（Post /open-apis/vc/v1/bots/join）。</summary>
    public Task<FeishuDataResponse> JoinAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/vc/v1/bots/join",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Leave /open-apis/vc/v1/bots/leave（Post /open-apis/vc/v1/bots/leave）。</summary>
    public Task<FeishuDataResponse> LeaveAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/vc/v1/bots/leave",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Message /open-apis/vc/v1/bots/message（Post /open-apis/vc/v1/bots/message）。</summary>
    public Task<FeishuDataResponse> MessageAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/vc/v1/bots/message",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>UserActiveMeeting /open-apis/vc/v1/bots/user_active_meeting（Get /open-apis/vc/v1/bots/user_active_meeting）。</summary>
    public Task<FeishuDataResponse> UserActiveMeetingAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/vc/v1/bots/user_active_meeting",
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class VcExportResource
{
    private readonly RequestPipeline _pipeline;

    internal VcExportResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Download /open-apis/vc/v1/exports/download（Get /open-apis/vc/v1/exports/download）。</summary>
    public Task<FeishuDataResponse> DownloadAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/vc/v1/exports/download",
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Get /open-apis/vc/v1/exports/:task_id（Get /open-apis/vc/v1/exports/:task_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string taskid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/vc/v1/exports/:task_id",
            PathParams =
            {
                ["task_id"] = taskid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>MeetingList /open-apis/vc/v1/exports/meeting_list（Post /open-apis/vc/v1/exports/meeting_list）。</summary>
    public Task<FeishuDataResponse> MeetingListAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/vc/v1/exports/meeting_list",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>ParticipantList /open-apis/vc/v1/exports/participant_list（Post /open-apis/vc/v1/exports/participant_list）。</summary>
    public Task<FeishuDataResponse> ParticipantListAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/vc/v1/exports/participant_list",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>ParticipantQualityList /open-apis/vc/v1/exports/participant_quality_list（Post /open-apis/vc/v1/exports/participant_quality_list）。</summary>
    public Task<FeishuDataResponse> ParticipantQualityListAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/vc/v1/exports/participant_quality_list",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>ResourceReservationList /open-apis/vc/v1/exports/resource_reservation_list（Post /open-apis/vc/v1/exports/resource_reservation_list）。</summary>
    public Task<FeishuDataResponse> ResourceReservationListAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/vc/v1/exports/resource_reservation_list",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class VcMeetingResource
{
    private readonly RequestPipeline _pipeline;

    internal VcMeetingResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>End /open-apis/vc/v1/meetings/:meeting_id/end（Patch /open-apis/vc/v1/meetings/:meeting_id/end）。</summary>
    public Task<FeishuDataResponse> EndAsync(string meetingid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/vc/v1/meetings/:meeting_id/end",
            PathParams =
            {
                ["meeting_id"] = meetingid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Get /open-apis/vc/v1/meetings/:meeting_id（Get /open-apis/vc/v1/meetings/:meeting_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string meetingid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/vc/v1/meetings/:meeting_id",
            PathParams =
            {
                ["meeting_id"] = meetingid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Invite /open-apis/vc/v1/meetings/:meeting_id/invite（Patch /open-apis/vc/v1/meetings/:meeting_id/invite）。</summary>
    public Task<FeishuDataResponse> InviteAsync(string meetingid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/vc/v1/meetings/:meeting_id/invite",
            PathParams =
            {
                ["meeting_id"] = meetingid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Kickout /open-apis/vc/v1/meetings/:meeting_id/kickout（Post /open-apis/vc/v1/meetings/:meeting_id/kickout）。</summary>
    public Task<FeishuDataResponse> KickoutAsync(string meetingid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/vc/v1/meetings/:meeting_id/kickout",
            PathParams =
            {
                ["meeting_id"] = meetingid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>ListByNo /open-apis/vc/v1/meetings/list_by_no（Get /open-apis/vc/v1/meetings/list_by_no）。</summary>
    public Task<FeishuDataResponse> ListByNoAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/vc/v1/meetings/list_by_no",
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Search /open-apis/vc/v1/meetings/search（Post /open-apis/vc/v1/meetings/search）。</summary>
    public Task<FeishuDataResponse> SearchAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/vc/v1/meetings/search",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>SetHost /open-apis/vc/v1/meetings/:meeting_id/set_host（Patch /open-apis/vc/v1/meetings/:meeting_id/set_host）。</summary>
    public Task<FeishuDataResponse> SetHostAsync(string meetingid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/vc/v1/meetings/:meeting_id/set_host",
            PathParams =
            {
                ["meeting_id"] = meetingid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Subscription /open-apis/vc/v1/meetings/subscription（Post /open-apis/vc/v1/meetings/subscription）。</summary>
    public Task<FeishuDataResponse> SubscriptionAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/vc/v1/meetings/subscription",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Unsubscription /open-apis/vc/v1/meetings/unsubscription（Post /open-apis/vc/v1/meetings/unsubscription）。</summary>
    public Task<FeishuDataResponse> UnsubscriptionAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/vc/v1/meetings/unsubscription",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class VcMeetingRecordingResource
{
    private readonly RequestPipeline _pipeline;

    internal VcMeetingRecordingResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Get /open-apis/vc/v1/meetings/:meeting_id/recording（Get /open-apis/vc/v1/meetings/:meeting_id/recording）。</summary>
    public Task<FeishuDataResponse> GetAsync(string meetingid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/vc/v1/meetings/:meeting_id/recording",
            PathParams =
            {
                ["meeting_id"] = meetingid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>SetPermission /open-apis/vc/v1/meetings/:meeting_id/recording/set_permission（Patch /open-apis/vc/v1/meetings/:meeting_id/recording/set_permission）。</summary>
    public Task<FeishuDataResponse> SetPermissionAsync(string meetingid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/vc/v1/meetings/:meeting_id/recording/set_permission",
            PathParams =
            {
                ["meeting_id"] = meetingid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Start /open-apis/vc/v1/meetings/:meeting_id/recording/start（Patch /open-apis/vc/v1/meetings/:meeting_id/recording/start）。</summary>
    public Task<FeishuDataResponse> StartAsync(string meetingid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/vc/v1/meetings/:meeting_id/recording/start",
            PathParams =
            {
                ["meeting_id"] = meetingid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Stop /open-apis/vc/v1/meetings/:meeting_id/recording/stop（Patch /open-apis/vc/v1/meetings/:meeting_id/recording/stop）。</summary>
    public Task<FeishuDataResponse> StopAsync(string meetingid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/vc/v1/meetings/:meeting_id/recording/stop",
            PathParams =
            {
                ["meeting_id"] = meetingid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class VcMeetingListResource
{
    private readonly RequestPipeline _pipeline;

    internal VcMeetingListResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Get /open-apis/vc/v1/meeting_list（Get /open-apis/vc/v1/meeting_list）。</summary>
    public Task<FeishuDataResponse> GetAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/vc/v1/meeting_list",
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class VcNoteResource
{
    private readonly RequestPipeline _pipeline;

    internal VcNoteResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Get /open-apis/vc/v1/notes/:note_id（Get /open-apis/vc/v1/notes/:note_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string noteid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/vc/v1/notes/:note_id",
            PathParams =
            {
                ["note_id"] = noteid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Subscription /open-apis/vc/v1/notes/subscription（Post /open-apis/vc/v1/notes/subscription）。</summary>
    public Task<FeishuDataResponse> SubscriptionAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/vc/v1/notes/subscription",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Unsubscription /open-apis/vc/v1/notes/unsubscription（Post /open-apis/vc/v1/notes/unsubscription）。</summary>
    public Task<FeishuDataResponse> UnsubscriptionAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/vc/v1/notes/unsubscription",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class VcParticipantListResource
{
    private readonly RequestPipeline _pipeline;

    internal VcParticipantListResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Get /open-apis/vc/v1/participant_list（Get /open-apis/vc/v1/participant_list）。</summary>
    public Task<FeishuDataResponse> GetAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/vc/v1/participant_list",
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class VcParticipantQualityListResource
{
    private readonly RequestPipeline _pipeline;

    internal VcParticipantQualityListResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Get /open-apis/vc/v1/participant_quality_list（Get /open-apis/vc/v1/participant_quality_list）。</summary>
    public Task<FeishuDataResponse> GetAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/vc/v1/participant_quality_list",
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class VcReportResource
{
    private readonly RequestPipeline _pipeline;

    internal VcReportResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>GetDaily /open-apis/vc/v1/reports/get_daily（Get /open-apis/vc/v1/reports/get_daily）。</summary>
    public Task<FeishuDataResponse> GetDailyAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/vc/v1/reports/get_daily",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>GetTopUser /open-apis/vc/v1/reports/get_top_user（Get /open-apis/vc/v1/reports/get_top_user）。</summary>
    public Task<FeishuDataResponse> GetTopUserAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/vc/v1/reports/get_top_user",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class VcReserveResource
{
    private readonly RequestPipeline _pipeline;

    internal VcReserveResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Apply /open-apis/vc/v1/reserves/apply（Post /open-apis/vc/v1/reserves/apply）。</summary>
    public Task<FeishuDataResponse> ApplyAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/vc/v1/reserves/apply",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Delete /open-apis/vc/v1/reserves/:reserve_id（Delete /open-apis/vc/v1/reserves/:reserve_id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string reserveid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/vc/v1/reserves/:reserve_id",
            PathParams =
            {
                ["reserve_id"] = reserveid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Get /open-apis/vc/v1/reserves/:reserve_id（Get /open-apis/vc/v1/reserves/:reserve_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string reserveid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/vc/v1/reserves/:reserve_id",
            PathParams =
            {
                ["reserve_id"] = reserveid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>GetActiveMeeting /open-apis/vc/v1/reserves/:reserve_id/get_active_meeting（Get /open-apis/vc/v1/reserves/:reserve_id/get_active_meeting）。</summary>
    public Task<FeishuDataResponse> GetActiveMeetingAsync(string reserveid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/vc/v1/reserves/:reserve_id/get_active_meeting",
            PathParams =
            {
                ["reserve_id"] = reserveid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Update /open-apis/vc/v1/reserves/:reserve_id（Put /open-apis/vc/v1/reserves/:reserve_id）。</summary>
    public Task<FeishuDataResponse> UpdateAsync(string reserveid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Put,
            Path = "/open-apis/vc/v1/reserves/:reserve_id",
            PathParams =
            {
                ["reserve_id"] = reserveid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class VcReserveConfigResource
{
    private readonly RequestPipeline _pipeline;

    internal VcReserveConfigResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Patch /open-apis/vc/v1/reserve_configs/:reserve_config_id（Patch /open-apis/vc/v1/reserve_configs/:reserve_config_id）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string reserveconfigid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/vc/v1/reserve_configs/:reserve_config_id",
            PathParams =
            {
                ["reserve_config_id"] = reserveconfigid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>ReserveScope /open-apis/vc/v1/reserve_configs/reserve_scope（Get /open-apis/vc/v1/reserve_configs/reserve_scope）。</summary>
    public Task<FeishuDataResponse> ReserveScopeAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/vc/v1/reserve_configs/reserve_scope",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class VcReserveConfigAdminResource
{
    private readonly RequestPipeline _pipeline;

    internal VcReserveConfigAdminResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Get /open-apis/vc/v1/reserve_configs/:reserve_config_id/admin（Get /open-apis/vc/v1/reserve_configs/:reserve_config_id/admin）。</summary>
    public Task<FeishuDataResponse> GetAsync(string reserveconfigid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/vc/v1/reserve_configs/:reserve_config_id/admin",
            PathParams =
            {
                ["reserve_config_id"] = reserveconfigid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Patch /open-apis/vc/v1/reserve_configs/:reserve_config_id/admin（Patch /open-apis/vc/v1/reserve_configs/:reserve_config_id/admin）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string reserveconfigid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/vc/v1/reserve_configs/:reserve_config_id/admin",
            PathParams =
            {
                ["reserve_config_id"] = reserveconfigid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class VcReserveConfigDisableInformResource
{
    private readonly RequestPipeline _pipeline;

    internal VcReserveConfigDisableInformResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Get /open-apis/vc/v1/reserve_configs/:reserve_config_id/disable_inform（Get /open-apis/vc/v1/reserve_configs/:reserve_config_id/disable_inform）。</summary>
    public Task<FeishuDataResponse> GetAsync(string reserveconfigid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/vc/v1/reserve_configs/:reserve_config_id/disable_inform",
            PathParams =
            {
                ["reserve_config_id"] = reserveconfigid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Patch /open-apis/vc/v1/reserve_configs/:reserve_config_id/disable_inform（Patch /open-apis/vc/v1/reserve_configs/:reserve_config_id/disable_inform）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string reserveconfigid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/vc/v1/reserve_configs/:reserve_config_id/disable_inform",
            PathParams =
            {
                ["reserve_config_id"] = reserveconfigid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class VcReserveConfigFormResource
{
    private readonly RequestPipeline _pipeline;

    internal VcReserveConfigFormResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Get /open-apis/vc/v1/reserve_configs/:reserve_config_id/form（Get /open-apis/vc/v1/reserve_configs/:reserve_config_id/form）。</summary>
    public Task<FeishuDataResponse> GetAsync(string reserveconfigid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/vc/v1/reserve_configs/:reserve_config_id/form",
            PathParams =
            {
                ["reserve_config_id"] = reserveconfigid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Patch /open-apis/vc/v1/reserve_configs/:reserve_config_id/form（Patch /open-apis/vc/v1/reserve_configs/:reserve_config_id/form）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string reserveconfigid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/vc/v1/reserve_configs/:reserve_config_id/form",
            PathParams =
            {
                ["reserve_config_id"] = reserveconfigid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class VcResourceReservationListResource
{
    private readonly RequestPipeline _pipeline;

    internal VcResourceReservationListResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Get /open-apis/vc/v1/resource_reservation_list（Get /open-apis/vc/v1/resource_reservation_list）。</summary>
    public Task<FeishuDataResponse> GetAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/vc/v1/resource_reservation_list",
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class VcRoomResource
{
    private readonly RequestPipeline _pipeline;

    internal VcRoomResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Create /open-apis/vc/v1/rooms（Post /open-apis/vc/v1/rooms）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/vc/v1/rooms",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Delete /open-apis/vc/v1/rooms/:room_id（Delete /open-apis/vc/v1/rooms/:room_id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string roomid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/vc/v1/rooms/:room_id",
            PathParams =
            {
                ["room_id"] = roomid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Get /open-apis/vc/v1/rooms/:room_id（Get /open-apis/vc/v1/rooms/:room_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string roomid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/vc/v1/rooms/:room_id",
            PathParams =
            {
                ["room_id"] = roomid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>List /open-apis/vc/v1/rooms（Get /open-apis/vc/v1/rooms）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/vc/v1/rooms",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Mget /open-apis/vc/v1/rooms/mget（Post /open-apis/vc/v1/rooms/mget）。</summary>
    public Task<FeishuDataResponse> MgetAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/vc/v1/rooms/mget",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Patch /open-apis/vc/v1/rooms/:room_id（Patch /open-apis/vc/v1/rooms/:room_id）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string roomid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/vc/v1/rooms/:room_id",
            PathParams =
            {
                ["room_id"] = roomid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Search /open-apis/vc/v1/rooms/search（Post /open-apis/vc/v1/rooms/search）。</summary>
    public Task<FeishuDataResponse> SearchAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/vc/v1/rooms/search",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class VcRoomConfigResource
{
    private readonly RequestPipeline _pipeline;

    internal VcRoomConfigResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Query /open-apis/vc/v1/room_configs/query（Get /open-apis/vc/v1/room_configs/query）。</summary>
    public Task<FeishuDataResponse> QueryAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/vc/v1/room_configs/query",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Set /open-apis/vc/v1/room_configs/set（Post /open-apis/vc/v1/room_configs/set）。</summary>
    public Task<FeishuDataResponse> SetAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/vc/v1/room_configs/set",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>SetCheckboardAccessCode /open-apis/vc/v1/room_configs/set_checkboard_access_code（Post /open-apis/vc/v1/room_configs/set_checkboard_access_code）。</summary>
    public Task<FeishuDataResponse> SetCheckboardAccessCodeAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/vc/v1/room_configs/set_checkboard_access_code",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>SetRoomAccessCode /open-apis/vc/v1/room_configs/set_room_access_code（Post /open-apis/vc/v1/room_configs/set_room_access_code）。</summary>
    public Task<FeishuDataResponse> SetRoomAccessCodeAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/vc/v1/room_configs/set_room_access_code",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class VcRoomLevelResource
{
    private readonly RequestPipeline _pipeline;

    internal VcRoomLevelResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Create /open-apis/vc/v1/room_levels（Post /open-apis/vc/v1/room_levels）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/vc/v1/room_levels",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Del /open-apis/vc/v1/room_levels/del（Post /open-apis/vc/v1/room_levels/del）。</summary>
    public Task<FeishuDataResponse> DelAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/vc/v1/room_levels/del",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Get /open-apis/vc/v1/room_levels/:room_level_id（Get /open-apis/vc/v1/room_levels/:room_level_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string roomlevelid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/vc/v1/room_levels/:room_level_id",
            PathParams =
            {
                ["room_level_id"] = roomlevelid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>List /open-apis/vc/v1/room_levels（Get /open-apis/vc/v1/room_levels）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/vc/v1/room_levels",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Mget /open-apis/vc/v1/room_levels/mget（Post /open-apis/vc/v1/room_levels/mget）。</summary>
    public Task<FeishuDataResponse> MgetAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/vc/v1/room_levels/mget",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Patch /open-apis/vc/v1/room_levels/:room_level_id（Patch /open-apis/vc/v1/room_levels/:room_level_id）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string roomlevelid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/vc/v1/room_levels/:room_level_id",
            PathParams =
            {
                ["room_level_id"] = roomlevelid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Search /open-apis/vc/v1/room_levels/search（Get /open-apis/vc/v1/room_levels/search）。</summary>
    public Task<FeishuDataResponse> SearchAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/vc/v1/room_levels/search",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class VcScopeConfigResource
{
    private readonly RequestPipeline _pipeline;

    internal VcScopeConfigResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Create /open-apis/vc/v1/scope_config（Post /open-apis/vc/v1/scope_config）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/vc/v1/scope_config",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Get /open-apis/vc/v1/scope_config（Get /open-apis/vc/v1/scope_config）。</summary>
    public Task<FeishuDataResponse> GetAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/vc/v1/scope_config",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

}
