// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.Task;

/// <summary>任务（task/v2 高频端点）（生成代码：5 个端点）。</summary>
public sealed class TaskService
{
    private readonly RequestPipeline _pipeline;

    internal TaskService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        Task = new TaskTaskResource(pipeline);
    }

    /// <summary>Task 资源。</summary>
    public TaskTaskResource Task { get; }

public sealed class TaskTaskResource
{
    private readonly RequestPipeline _pipeline;

    internal TaskTaskResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>创建任务（POST /open-apis/task/v2/tasks）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/task/v2/tasks",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取任务详情（GET /open-apis/task/v2/tasks/:task_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string taskid, IDictionary<string, string>? query = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/task/v2/tasks/:task_id",
            PathParams =
            {
                ["task_id"] = taskid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>更新任务（PATCH /open-apis/task/v2/tasks/:task_id）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string taskid, IDictionary<string, string>? query = null, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/task/v2/tasks/:task_id",
            PathParams =
            {
                ["task_id"] = taskid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>完成任务（POST /open-apis/task/v2/tasks/:task_id/complete）。</summary>
    public Task<FeishuDataResponse> CompleteAsync(string taskid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/task/v2/tasks/:task_id/complete",
            PathParams =
            {
                ["task_id"] = taskid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取任务列表（分页）（GET /open-apis/task/v2/tasks）。</summary>
    public Task<FeishuDataResponse> ListAsync(IDictionary<string, string>? query = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/task/v2/tasks",
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取任务列表（分页）：自动翻页枚举 data.items。</summary>
    public async IAsyncEnumerable<System.Text.Json.JsonElement> ListAsyncEnumerate(IDictionary<string, string>? query = null, RequestOptions? options = null, int? limit = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var emitted = 0;
        string? pageToken = null;
        do
        {
            var pageQuery = query == null ? new Dictionary<string, string>() : new Dictionary<string, string>(query);
            if (pageToken != null) pageQuery["page_token"] = pageToken;
            var page = await ListAsync(pageQuery, options, cancellationToken);
            page.EnsureSuccess();
            if (page.Data is not { ValueKind: System.Text.Json.JsonValueKind.Object } data) yield break;
            if (!data.TryGetProperty("items", out var items) || items.ValueKind != System.Text.Json.JsonValueKind.Array) yield break;
            foreach (var item in items.EnumerateArray())
            {
                if (limit.HasValue && emitted >= limit.Value) yield break;
                emitted++;
                yield return item;
            }
            pageToken = page.PageToken is { Length: > 0 } ? page.PageToken : null;
        } while (pageToken != null);
    }

}

}
