// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.Minutes;

/// <summary>妙记（minutes/v1）（生成代码：8 个端点）。</summary>
public sealed class MinutesService
{
    private readonly RequestPipeline _pipeline;

    internal MinutesService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        Minute = new MinutesMinuteResource(pipeline);
        MinuteMedia = new MinutesMinuteMediaResource(pipeline);
        MinuteStatistics = new MinutesMinuteStatisticsResource(pipeline);
        MinuteTranscript = new MinutesMinuteTranscriptResource(pipeline);
    }

    /// <summary>Minute 资源。</summary>
    public MinutesMinuteResource Minute { get; }
    /// <summary>MinuteMedia 资源。</summary>
    public MinutesMinuteMediaResource MinuteMedia { get; }
    /// <summary>MinuteStatistics 资源。</summary>
    public MinutesMinuteStatisticsResource MinuteStatistics { get; }
    /// <summary>MinuteTranscript 资源。</summary>
    public MinutesMinuteTranscriptResource MinuteTranscript { get; }

public sealed class MinutesMinuteResource
{
    private readonly RequestPipeline _pipeline;

    internal MinutesMinuteResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>获取单个妙记信息（GET /open-apis/minutes/v1/minutes/:minute_token）。</summary>
    public Task<FeishuDataResponse> GetAsync(string minutetoken, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/minutes/v1/minutes/:minute_token",
            PathParams =
            {
                ["minute_token"] = minutetoken,
            },
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取妙记AI产物（GET /open-apis/minutes/v1/minutes/:minute_token/artifacts）。</summary>
    public Task<FeishuDataResponse> ArtifactsAsync(string minutetoken, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/minutes/v1/minutes/:minute_token/artifacts",
            PathParams =
            {
                ["minute_token"] = minutetoken,
            },
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>搜索妙记（POST /open-apis/minutes/v1/minutes/search）。</summary>
    public Task<FeishuDataResponse> SearchAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/minutes/v1/minutes/search",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>订阅妙记变更事件（POST /open-apis/minutes/v1/minutes/subscription）。</summary>
    public Task<FeishuDataResponse> SubscriptionAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/minutes/v1/minutes/subscription",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>取消订阅妙记变更事件（POST /open-apis/minutes/v1/minutes/unsubscription）。</summary>
    public Task<FeishuDataResponse> UnsubscriptionAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/minutes/v1/minutes/unsubscription",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class MinutesMinuteMediaResource
{
    private readonly RequestPipeline _pipeline;

    internal MinutesMinuteMediaResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>获取妙记音视频文件（GET /open-apis/minutes/v1/minutes/:minute_token/media）。</summary>
    public Task<FeishuDataResponse> GetAsync(string minutetoken, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/minutes/v1/minutes/:minute_token/media",
            PathParams =
            {
                ["minute_token"] = minutetoken,
            },
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class MinutesMinuteStatisticsResource
{
    private readonly RequestPipeline _pipeline;

    internal MinutesMinuteStatisticsResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>获取妙记统计数据（GET /open-apis/minutes/v1/minutes/:minute_token/statistics）。</summary>
    public Task<FeishuDataResponse> GetAsync(string minutetoken, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/minutes/v1/minutes/:minute_token/statistics",
            PathParams =
            {
                ["minute_token"] = minutetoken,
            },
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class MinutesMinuteTranscriptResource
{
    private readonly RequestPipeline _pipeline;

    internal MinutesMinuteTranscriptResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>导出妙记文字记录（GET /open-apis/minutes/v1/minutes/:minute_token/transcript）。</summary>
    public Task<ApiResponse> GetAsync(string minutetoken, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/minutes/v1/minutes/:minute_token/transcript",
            PathParams =
            {
                ["minute_token"] = minutetoken,
            },
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        options = (options ?? RequestOptions.Default).WithFileDownload();
        return _pipeline.SendAsync(api, options, cancellationToken);
    }

}

}
