// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.Ehr;

/// <summary>电子劳动合同（ehr/v1）（生成代码：2 个端点）。</summary>
public sealed class EhrService
{
    private readonly RequestPipeline _pipeline;

    internal EhrService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        Attachment = new EhrAttachmentResource(pipeline);
        Employee = new EhrEmployeeResource(pipeline);
    }

    /// <summary>Attachment 资源。</summary>
    public EhrAttachmentResource Attachment { get; }
    /// <summary>Employee 资源。</summary>
    public EhrEmployeeResource Employee { get; }

public sealed class EhrAttachmentResource
{
    private readonly RequestPipeline _pipeline;

    internal EhrAttachmentResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>下载人员的附件（GET /open-apis/ehr/v1/attachments/:token）。</summary>
    public Task<ApiResponse> GetAsync(string token, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/ehr/v1/attachments/:token",
            PathParams =
            {
                ["token"] = token,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        options = (options ?? RequestOptions.Default).WithFileDownload();
        return _pipeline.SendAsync(api, options, cancellationToken);
    }

}

public sealed class EhrEmployeeResource
{
    private readonly RequestPipeline _pipeline;

    internal EhrEmployeeResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>批量获取员工花名册信息（GET /open-apis/ehr/v1/employees）。</summary>
    public Task<FeishuDataResponse> ListAsync(IDictionary<string, string>? query = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/ehr/v1/employees",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>批量获取员工花名册信息：自动翻页枚举 data.items。</summary>
    public async IAsyncEnumerable<System.Text.Json.JsonElement> ListAsyncEnumerate(IDictionary<string, string>? query = null, RequestOptions? options = null, int? limit = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var emitted = 0;
        string? pageToken = null;
        do
        {
            var pageQuery = query == null ? new Dictionary<string, string>() : new Dictionary<string, string>(query);
            if (pageToken != null) pageQuery["page_token"] = pageToken;
            var page = await ListAsync(pageQuery, options, cancellationToken);
            page.EnsureSuccess();
            if (page.Data is not { ValueKind: System.Text.Json.JsonValueKind.Object } data) yield break;
            if (!data.TryGetProperty("items", out var items) || items.ValueKind != System.Text.Json.JsonValueKind.Array) yield break;
            foreach (var item in items.EnumerateArray())
            {
                if (limit.HasValue && emitted >= limit.Value) yield break;
                emitted++;
                yield return item;
            }
            pageToken = page.PageToken is { Length: > 0 } ? page.PageToken : null;
        } while (pageToken != null);
    }

}

}
