// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.Payroll;

/// <summary>算薪（payroll/v1）（生成代码：12 个端点）。</summary>
public sealed class PayrollService
{
    private readonly RequestPipeline _pipeline;

    internal PayrollService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        AcctItem = new PayrollAcctItemResource(pipeline);
        CostAllocationDetail = new PayrollCostAllocationDetailResource(pipeline);
        CostAllocationPlan = new PayrollCostAllocationPlanResource(pipeline);
        CostAllocationReport = new PayrollCostAllocationReportResource(pipeline);
        Datasource = new PayrollDatasourceResource(pipeline);
        DatasourceRecord = new PayrollDatasourceRecordResource(pipeline);
        Paygroup = new PayrollPaygroupResource(pipeline);
        PaymentActivity = new PayrollPaymentActivityResource(pipeline);
        PaymentActivityDetail = new PayrollPaymentActivityDetailResource(pipeline);
        PaymentDetail = new PayrollPaymentDetailResource(pipeline);
    }

    /// <summary>AcctItem 资源。</summary>
    public PayrollAcctItemResource AcctItem { get; }
    /// <summary>CostAllocationDetail 资源。</summary>
    public PayrollCostAllocationDetailResource CostAllocationDetail { get; }
    /// <summary>CostAllocationPlan 资源。</summary>
    public PayrollCostAllocationPlanResource CostAllocationPlan { get; }
    /// <summary>CostAllocationReport 资源。</summary>
    public PayrollCostAllocationReportResource CostAllocationReport { get; }
    /// <summary>Datasource 资源。</summary>
    public PayrollDatasourceResource Datasource { get; }
    /// <summary>DatasourceRecord 资源。</summary>
    public PayrollDatasourceRecordResource DatasourceRecord { get; }
    /// <summary>Paygroup 资源。</summary>
    public PayrollPaygroupResource Paygroup { get; }
    /// <summary>PaymentActivity 资源。</summary>
    public PayrollPaymentActivityResource PaymentActivity { get; }
    /// <summary>PaymentActivityDetail 资源。</summary>
    public PayrollPaymentActivityDetailResource PaymentActivityDetail { get; }
    /// <summary>PaymentDetail 资源。</summary>
    public PayrollPaymentDetailResource PaymentDetail { get; }

public sealed class PayrollAcctItemResource
{
    private readonly RequestPipeline _pipeline;

    internal PayrollAcctItemResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>批量查询算薪项（GET /open-apis/payroll/v1/acct_items）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/payroll/v1/acct_items",
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class PayrollCostAllocationDetailResource
{
    private readonly RequestPipeline _pipeline;

    internal PayrollCostAllocationDetailResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>查询成本分摊报表明细（GET /open-apis/payroll/v1/cost_allocation_details）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/payroll/v1/cost_allocation_details",
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class PayrollCostAllocationPlanResource
{
    private readonly RequestPipeline _pipeline;

    internal PayrollCostAllocationPlanResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>批量查询成本分摊方案（GET /open-apis/payroll/v1/cost_allocation_plans）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/payroll/v1/cost_allocation_plans",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class PayrollCostAllocationReportResource
{
    private readonly RequestPipeline _pipeline;

    internal PayrollCostAllocationReportResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>查询成本分摊报表汇总（GET /open-apis/payroll/v1/cost_allocation_reports）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/payroll/v1/cost_allocation_reports",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class PayrollDatasourceResource
{
    private readonly RequestPipeline _pipeline;

    internal PayrollDatasourceResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>获取外部数据源配置（GET /open-apis/payroll/v1/datasources）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/payroll/v1/datasources",
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class PayrollDatasourceRecordResource
{
    private readonly RequestPipeline _pipeline;

    internal PayrollDatasourceRecordResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>批量查询外部算薪数据记录（POST /open-apis/payroll/v1/datasource_records/query）。</summary>
    public Task<FeishuDataResponse> QueryAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/payroll/v1/datasource_records/query",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>创建/更新外部算薪数据（POST /open-apis/payroll/v1/datasource_records/save）。</summary>
    public Task<FeishuDataResponse> SaveAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/payroll/v1/datasource_records/save",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class PayrollPaygroupResource
{
    private readonly RequestPipeline _pipeline;

    internal PayrollPaygroupResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>获取薪资组基本信息（GET /open-apis/payroll/v1/paygroups）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/payroll/v1/paygroups",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class PayrollPaymentActivityResource
{
    private readonly RequestPipeline _pipeline;

    internal PayrollPaymentActivityResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>查询发薪活动列表（GET /open-apis/payroll/v1/payment_activitys）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/payroll/v1/payment_activitys",
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>封存发薪活动（POST /open-apis/payroll/v1/payment_activitys/archive）。</summary>
    public Task<FeishuDataResponse> ArchiveAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/payroll/v1/payment_activitys/archive",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class PayrollPaymentActivityDetailResource
{
    private readonly RequestPipeline _pipeline;

    internal PayrollPaymentActivityDetailResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>查询发薪活动明细列表（GET /open-apis/payroll/v1/payment_activity_details）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/payroll/v1/payment_activity_details",
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class PayrollPaymentDetailResource
{
    private readonly RequestPipeline _pipeline;

    internal PayrollPaymentDetailResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>批量查询发薪明细（POST /open-apis/payroll/v1/payment_detail/query）。</summary>
    public Task<FeishuDataResponse> QueryAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/payroll/v1/payment_detail/query",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

}
