// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.Tenant;

/// <summary>租户信息（tenant/v2）（生成代码：1 个端点）。</summary>
public sealed class TenantService
{
    private readonly RequestPipeline _pipeline;

    internal TenantService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        Tenant = new TenantTenantResource(pipeline);
    }

    /// <summary>Tenant 资源。</summary>
    public TenantTenantResource Tenant { get; }

public sealed class TenantTenantResource
{
    private readonly RequestPipeline _pipeline;

    internal TenantTenantResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>获取企业信息（GET /open-apis/tenant/v2/tenant/query）。</summary>
    public Task<FeishuDataResponse> QueryAsync(IDictionary<string, string>? query = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/tenant/v2/tenant/query",
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

}
