// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.UnifiedKms;

/// <summary>统一密钥管理（unified_kms/v1）（生成代码：8 个端点）。</summary>
public sealed class UnifiedKmsService
{
    private readonly RequestPipeline _pipeline;

    internal UnifiedKmsService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        AutonomousKey = new UnifiedKmsAutonomousKeyResource(pipeline);
        AutonomousKeyDeletionPlan = new UnifiedKmsAutonomousKeyDeletionPlanResource(pipeline);
        AutonomousKeyRecover = new UnifiedKmsAutonomousKeyRecoverResource(pipeline);
        KeyImportMaterial = new UnifiedKmsKeyImportMaterialResource(pipeline);
    }

    /// <summary>AutonomousKey 资源。</summary>
    public UnifiedKmsAutonomousKeyResource AutonomousKey { get; }
    /// <summary>AutonomousKeyDeletionPlan 资源。</summary>
    public UnifiedKmsAutonomousKeyDeletionPlanResource AutonomousKeyDeletionPlan { get; }
    /// <summary>AutonomousKeyRecover 资源。</summary>
    public UnifiedKmsAutonomousKeyRecoverResource AutonomousKeyRecover { get; }
    /// <summary>KeyImportMaterial 资源。</summary>
    public UnifiedKmsKeyImportMaterialResource KeyImportMaterial { get; }

public sealed class UnifiedKmsAutonomousKeyResource
{
    private readonly RequestPipeline _pipeline;

    internal UnifiedKmsAutonomousKeyResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>导入与轮转密钥（POST /open-apis/unified_kms/v1/autonomous_keys）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/unified_kms/v1/autonomous_keys",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取密钥信息（GET /open-apis/unified_kms/v1/autonomous_keys/:key_version_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string keyversionid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/unified_kms/v1/autonomous_keys/:key_version_id",
            PathParams =
            {
                ["key_version_id"] = keyversionid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>批量获取密钥信息（GET /open-apis/unified_kms/v1/autonomous_keys）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/unified_kms/v1/autonomous_keys",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>立即删除密钥（DELETE /open-apis/unified_kms/v1/autonomous_keys/:key_version_id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string keyversionid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/unified_kms/v1/autonomous_keys/:key_version_id",
            PathParams =
            {
                ["key_version_id"] = keyversionid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class UnifiedKmsAutonomousKeyDeletionPlanResource
{
    private readonly RequestPipeline _pipeline;

    internal UnifiedKmsAutonomousKeyDeletionPlanResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>创建密钥删除计划（POST /open-apis/unified_kms/v1/autonomous_keys/:key_version_id/deletion_plan）。</summary>
    public Task<FeishuDataResponse> CreateAsync(string keyversionid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/unified_kms/v1/autonomous_keys/:key_version_id/deletion_plan",
            PathParams =
            {
                ["key_version_id"] = keyversionid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>取消密钥删除计划（DELETE /open-apis/unified_kms/v1/autonomous_keys/:key_version_id/deletion_plan）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string keyversionid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/unified_kms/v1/autonomous_keys/:key_version_id/deletion_plan",
            PathParams =
            {
                ["key_version_id"] = keyversionid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class UnifiedKmsAutonomousKeyRecoverResource
{
    private readonly RequestPipeline _pipeline;

    internal UnifiedKmsAutonomousKeyRecoverResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>恢复已删除的主密钥（POST /open-apis/unified_kms/v1/autonomous_keys/:key_version_id/recover）。</summary>
    public Task<FeishuDataResponse> CreateAsync(string keyversionid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/unified_kms/v1/autonomous_keys/:key_version_id/recover",
            PathParams =
            {
                ["key_version_id"] = keyversionid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class UnifiedKmsKeyImportMaterialResource
{
    private readonly RequestPipeline _pipeline;

    internal UnifiedKmsKeyImportMaterialResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>获取密钥导入材料（GET /open-apis/unified_kms/v1/key_import_material）。</summary>
    public Task<FeishuDataResponse> GetAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/unified_kms/v1/key_import_material",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

}
