// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.Translation;

/// <summary>机器翻译（translation/v1）（生成代码：2 个端点）。</summary>
public sealed class TranslationService
{
    private readonly RequestPipeline _pipeline;

    internal TranslationService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        Text = new TranslationTextResource(pipeline);
    }

    /// <summary>Text 资源。</summary>
    public TranslationTextResource Text { get; }

public sealed class TranslationTextResource
{
    private readonly RequestPipeline _pipeline;

    internal TranslationTextResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>识别文本语种（POST /open-apis/translation/v1/text/detect）。</summary>
    public Task<FeishuDataResponse> DetectAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/translation/v1/text/detect",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>翻译文本（POST /open-apis/translation/v1/text/translate）。</summary>
    public Task<FeishuDataResponse> TranslateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/translation/v1/text/translate",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

}
