// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.TrustParty;

/// <summary>信任组织（trust_party/v1）（生成代码：5 个端点）。</summary>
public sealed class TrustPartyService
{
    private readonly RequestPipeline _pipeline;

    internal TrustPartyService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        CollaborationTenant = new TrustPartyCollaborationTenantResource(pipeline);
        CollaborationDepartment = new TrustPartyCollaborationDepartmentResource(pipeline);
        CollaborationUser = new TrustPartyCollaborationUserResource(pipeline);
    }

    /// <summary>CollaborationTenant 资源。</summary>
    public TrustPartyCollaborationTenantResource CollaborationTenant { get; }
    /// <summary>CollaborationDepartment 资源。</summary>
    public TrustPartyCollaborationDepartmentResource CollaborationDepartment { get; }
    /// <summary>CollaborationUser 资源。</summary>
    public TrustPartyCollaborationUserResource CollaborationUser { get; }

public sealed class TrustPartyCollaborationTenantResource
{
    private readonly RequestPipeline _pipeline;

    internal TrustPartyCollaborationTenantResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>获取关联组织详情（GET /open-apis/trust_party/v1/collaboration_tenants/:target_tenant_key）。</summary>
    public Task<FeishuDataResponse> GetAsync(string targettenantkey, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/trust_party/v1/collaboration_tenants/:target_tenant_key",
            PathParams =
            {
                ["target_tenant_key"] = targettenantkey,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取可见关联组织列表（GET /open-apis/trust_party/v1/collaboration_tenants）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/trust_party/v1/collaboration_tenants",
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取关联组织成员信息（GET /open-apis/trust_party/v1/collaboration_tenants/:target_tenant_key/visible_organization）。</summary>
    public Task<FeishuDataResponse> VisibleOrganizationAsync(string targettenantkey, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/trust_party/v1/collaboration_tenants/:target_tenant_key/visible_organization",
            PathParams =
            {
                ["target_tenant_key"] = targettenantkey,
            },
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class TrustPartyCollaborationDepartmentResource
{
    private readonly RequestPipeline _pipeline;

    internal TrustPartyCollaborationDepartmentResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>获取关联组织部门详情（GET /open-apis/trust_party/v1/collaboration_tenants/:target_tenant_key/collaboration_departments/:target_department_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string targettenantkey, string targetdepartmentid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/trust_party/v1/collaboration_tenants/:target_tenant_key/collaboration_departments/:target_department_id",
            PathParams =
            {
                ["target_tenant_key"] = targettenantkey,
                ["target_department_id"] = targetdepartmentid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class TrustPartyCollaborationUserResource
{
    private readonly RequestPipeline _pipeline;

    internal TrustPartyCollaborationUserResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>获取关联组织成员详情（GET /open-apis/trust_party/v1/collaboration_tenants/:target_tenant_key/collaboration_users/:target_user_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string targettenantkey, string targetuserid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/trust_party/v1/collaboration_tenants/:target_tenant_key/collaboration_users/:target_user_id",
            PathParams =
            {
                ["target_tenant_key"] = targettenantkey,
                ["target_user_id"] = targetuserid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

}
