// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.Helpdesk;

/// <summary>服务台（helpdesk/v1）（生成代码：44 个端点）。</summary>
public sealed class HelpdeskService
{
    private readonly RequestPipeline _pipeline;

    internal HelpdeskService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        Agent = new HelpdeskAgentResource(pipeline);
        AgentSchedule = new HelpdeskAgentScheduleResource(pipeline);
        AgentSkill = new HelpdeskAgentSkillResource(pipeline);
        AgentSkillRule = new HelpdeskAgentSkillRuleResource(pipeline);
        BotMessage = new HelpdeskBotMessageResource(pipeline);
        Category = new HelpdeskCategoryResource(pipeline);
        Event = new HelpdeskEventResource(pipeline);
        Faq = new HelpdeskFaqResource(pipeline);
        Notification = new HelpdeskNotificationResource(pipeline);
        Ticket = new HelpdeskTicketResource(pipeline);
        TicketMessage = new HelpdeskTicketMessageResource(pipeline);
    }

    /// <summary>Agent 资源。</summary>
    public HelpdeskAgentResource Agent { get; }
    /// <summary>AgentSchedule 资源。</summary>
    public HelpdeskAgentScheduleResource AgentSchedule { get; }
    /// <summary>AgentSkill 资源。</summary>
    public HelpdeskAgentSkillResource AgentSkill { get; }
    /// <summary>AgentSkillRule 资源。</summary>
    public HelpdeskAgentSkillRuleResource AgentSkillRule { get; }
    /// <summary>BotMessage 资源。</summary>
    public HelpdeskBotMessageResource BotMessage { get; }
    /// <summary>Category 资源。</summary>
    public HelpdeskCategoryResource Category { get; }
    /// <summary>Event 资源。</summary>
    public HelpdeskEventResource Event { get; }
    /// <summary>Faq 资源。</summary>
    public HelpdeskFaqResource Faq { get; }
    /// <summary>Notification 资源。</summary>
    public HelpdeskNotificationResource Notification { get; }
    /// <summary>Ticket 资源。</summary>
    public HelpdeskTicketResource Ticket { get; }
    /// <summary>TicketMessage 资源。</summary>
    public HelpdeskTicketMessageResource TicketMessage { get; }

public sealed class HelpdeskAgentResource
{
    private readonly RequestPipeline _pipeline;

    internal HelpdeskAgentResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>获取客服邮箱（GET /open-apis/helpdesk/v1/agent_emails）。</summary>
    public Task<FeishuDataResponse> AgentEmailAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/helpdesk/v1/agent_emails",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>更新客服信息（PATCH /open-apis/helpdesk/v1/agents/:agent_id）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string agentid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/helpdesk/v1/agents/:agent_id",
            PathParams =
            {
                ["agent_id"] = agentid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class HelpdeskAgentScheduleResource
{
    private readonly RequestPipeline _pipeline;

    internal HelpdeskAgentScheduleResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>查询全部客服工作日程（GET /open-apis/helpdesk/v1/agent_schedules）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/helpdesk/v1/agent_schedules",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>创建客服工作日程（POST /open-apis/helpdesk/v1/agent_schedules）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/helpdesk/v1/agent_schedules",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>查询指定客服工作日程（GET /open-apis/helpdesk/v1/agents/:agent_id/schedules）。</summary>
    public Task<FeishuDataResponse> GetAsync(string agentid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/helpdesk/v1/agents/:agent_id/schedules",
            PathParams =
            {
                ["agent_id"] = agentid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>更新客服工作日程（PATCH /open-apis/helpdesk/v1/agents/:agent_id/schedules）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string agentid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/helpdesk/v1/agents/:agent_id/schedules",
            PathParams =
            {
                ["agent_id"] = agentid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>删除客服工作日程（DELETE /open-apis/helpdesk/v1/agents/:agent_id/schedules）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string agentid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/helpdesk/v1/agents/:agent_id/schedules",
            PathParams =
            {
                ["agent_id"] = agentid,
            },
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class HelpdeskAgentSkillResource
{
    private readonly RequestPipeline _pipeline;

    internal HelpdeskAgentSkillResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>查询全部客服技能（GET /open-apis/helpdesk/v1/agent_skills）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/helpdesk/v1/agent_skills",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>查询指定客服技能（GET /open-apis/helpdesk/v1/agent_skills/:agent_skill_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string agentskillid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/helpdesk/v1/agent_skills/:agent_skill_id",
            PathParams =
            {
                ["agent_skill_id"] = agentskillid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>创建客服技能（POST /open-apis/helpdesk/v1/agent_skills）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/helpdesk/v1/agent_skills",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>更新客服技能（PATCH /open-apis/helpdesk/v1/agent_skills/:agent_skill_id）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string agentskillid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/helpdesk/v1/agent_skills/:agent_skill_id",
            PathParams =
            {
                ["agent_skill_id"] = agentskillid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>删除客服技能（DELETE /open-apis/helpdesk/v1/agent_skills/:agent_skill_id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string agentskillid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/helpdesk/v1/agent_skills/:agent_skill_id",
            PathParams =
            {
                ["agent_skill_id"] = agentskillid,
            },
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class HelpdeskAgentSkillRuleResource
{
    private readonly RequestPipeline _pipeline;

    internal HelpdeskAgentSkillRuleResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>获取客服技能规则列表（GET /open-apis/helpdesk/v1/agent_skill_rules）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/helpdesk/v1/agent_skill_rules",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class HelpdeskBotMessageResource
{
    private readonly RequestPipeline _pipeline;

    internal HelpdeskBotMessageResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>服务台机器人向工单绑定群发送消息（POST /open-apis/helpdesk/v1/message）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/helpdesk/v1/message",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class HelpdeskCategoryResource
{
    private readonly RequestPipeline _pipeline;

    internal HelpdeskCategoryResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>获取全部知识库分类（GET /open-apis/helpdesk/v1/categories）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/helpdesk/v1/categories",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取知识库分类（GET /open-apis/helpdesk/v1/categories/:id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string id, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/helpdesk/v1/categories/:id",
            PathParams =
            {
                ["id"] = id,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>创建知识库分类（POST /open-apis/helpdesk/v1/categories）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/helpdesk/v1/categories",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>更新知识库分类详情（PATCH /open-apis/helpdesk/v1/categories/:id）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string id, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/helpdesk/v1/categories/:id",
            PathParams =
            {
                ["id"] = id,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>删除知识库分类（DELETE /open-apis/helpdesk/v1/categories/:id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string id, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/helpdesk/v1/categories/:id",
            PathParams =
            {
                ["id"] = id,
            },
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class HelpdeskEventResource
{
    private readonly RequestPipeline _pipeline;

    internal HelpdeskEventResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>订阅服务台事件（POST /open-apis/helpdesk/v1/events/subscribe）。</summary>
    public Task<FeishuDataResponse> SubscribeAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/helpdesk/v1/events/subscribe",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>取消订阅服务台事件（POST /open-apis/helpdesk/v1/events/unsubscribe）。</summary>
    public Task<FeishuDataResponse> UnsubscribeAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/helpdesk/v1/events/unsubscribe",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class HelpdeskFaqResource
{
    private readonly RequestPipeline _pipeline;

    internal HelpdeskFaqResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>获取全部知识库详情（GET /open-apis/helpdesk/v1/faqs）。</summary>
    public Task<FeishuDataResponse> ListAsync(IDictionary<string, string>? query = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/helpdesk/v1/faqs",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取全部知识库详情：自动翻页枚举 data.items。</summary>
    public async IAsyncEnumerable<System.Text.Json.JsonElement> ListAsyncEnumerate(IDictionary<string, string>? query = null, RequestOptions? options = null, int? limit = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var emitted = 0;
        string? pageToken = null;
        do
        {
            var pageQuery = query == null ? new Dictionary<string, string>() : new Dictionary<string, string>(query);
            if (pageToken != null) pageQuery["page_token"] = pageToken;
            var page = await ListAsync(pageQuery, options, cancellationToken);
            page.EnsureSuccess();
            if (page.Data is not { ValueKind: System.Text.Json.JsonValueKind.Object } data) yield break;
            if (!data.TryGetProperty("items", out var items) || items.ValueKind != System.Text.Json.JsonValueKind.Array) yield break;
            foreach (var item in items.EnumerateArray())
            {
                if (limit.HasValue && emitted >= limit.Value) yield break;
                emitted++;
                yield return item;
            }
            pageToken = page.PageToken is { Length: > 0 } ? page.PageToken : null;
        } while (pageToken != null);
    }

    /// <summary>获取指定知识库详情（GET /open-apis/helpdesk/v1/faqs/:id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string id, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/helpdesk/v1/faqs/:id",
            PathParams =
            {
                ["id"] = id,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>创建知识库（POST /open-apis/helpdesk/v1/faqs）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/helpdesk/v1/faqs",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>修改知识库（PATCH /open-apis/helpdesk/v1/faqs/:id）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string id, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/helpdesk/v1/faqs/:id",
            PathParams =
            {
                ["id"] = id,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>删除知识库（DELETE /open-apis/helpdesk/v1/faqs/:id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string id, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/helpdesk/v1/faqs/:id",
            PathParams =
            {
                ["id"] = id,
            },
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>搜索知识库（GET /open-apis/helpdesk/v1/faqs/search）。</summary>
    public Task<FeishuDataResponse> SearchAsync(IDictionary<string, string>? query = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/helpdesk/v1/faqs/search",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>搜索知识库：自动翻页枚举 data.items。</summary>
    public async IAsyncEnumerable<System.Text.Json.JsonElement> SearchAsyncEnumerate(IDictionary<string, string>? query = null, RequestOptions? options = null, int? limit = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var emitted = 0;
        string? pageToken = null;
        do
        {
            var pageQuery = query == null ? new Dictionary<string, string>() : new Dictionary<string, string>(query);
            if (pageToken != null) pageQuery["page_token"] = pageToken;
            var page = await SearchAsync(pageQuery, options, cancellationToken);
            page.EnsureSuccess();
            if (page.Data is not { ValueKind: System.Text.Json.JsonValueKind.Object } data) yield break;
            if (!data.TryGetProperty("items", out var items) || items.ValueKind != System.Text.Json.JsonValueKind.Array) yield break;
            foreach (var item in items.EnumerateArray())
            {
                if (limit.HasValue && emitted >= limit.Value) yield break;
                emitted++;
                yield return item;
            }
            pageToken = page.PageToken is { Length: > 0 } ? page.PageToken : null;
        } while (pageToken != null);
    }

    /// <summary>获取知识库图像（GET /open-apis/helpdesk/v1/faqs/:id/image/:image_key）。</summary>
    public Task<ApiResponse> FaqImageAsync(string id, string imagekey, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/helpdesk/v1/faqs/:id/image/:image_key",
            PathParams =
            {
                ["id"] = id,
                ["image_key"] = imagekey,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        options = (options ?? RequestOptions.Default).WithFileDownload();
        return _pipeline.SendAsync(api, options, cancellationToken);
    }

}

public sealed class HelpdeskNotificationResource
{
    private readonly RequestPipeline _pipeline;

    internal HelpdeskNotificationResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>创建推送（POST /open-apis/helpdesk/v1/notifications）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/helpdesk/v1/notifications",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>查询推送（GET /open-apis/helpdesk/v1/notifications/:notification_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string notificationid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/helpdesk/v1/notifications/:notification_id",
            PathParams =
            {
                ["notification_id"] = notificationid,
            },
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>更新推送（PATCH /open-apis/helpdesk/v1/notifications/:notification_id）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string notificationid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/helpdesk/v1/notifications/:notification_id",
            PathParams =
            {
                ["notification_id"] = notificationid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>提交审核（POST /open-apis/helpdesk/v1/notifications/:notification_id/submit_approve）。</summary>
    public Task<FeishuDataResponse> SubmitApproveAsync(string notificationid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/helpdesk/v1/notifications/:notification_id/submit_approve",
            PathParams =
            {
                ["notification_id"] = notificationid,
            },
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>取消审核（POST /open-apis/helpdesk/v1/notifications/:notification_id/cancel_approve）。</summary>
    public Task<FeishuDataResponse> CancelApproveAsync(string notificationid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/helpdesk/v1/notifications/:notification_id/cancel_approve",
            PathParams =
            {
                ["notification_id"] = notificationid,
            },
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>执行推送（POST /open-apis/helpdesk/v1/notifications/:notification_id/execute_send）。</summary>
    public Task<FeishuDataResponse> ExecuteSendAsync(string notificationid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/helpdesk/v1/notifications/:notification_id/execute_send",
            PathParams =
            {
                ["notification_id"] = notificationid,
            },
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>取消推送（POST /open-apis/helpdesk/v1/notifications/:notification_id/cancel_send）。</summary>
    public Task<FeishuDataResponse> CancelSendAsync(string notificationid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/helpdesk/v1/notifications/:notification_id/cancel_send",
            PathParams =
            {
                ["notification_id"] = notificationid,
            },
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>预览推送（POST /open-apis/helpdesk/v1/notifications/:notification_id/preview）。</summary>
    public Task<FeishuDataResponse> PreviewAsync(string notificationid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/helpdesk/v1/notifications/:notification_id/preview",
            PathParams =
            {
                ["notification_id"] = notificationid,
            },
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class HelpdeskTicketResource
{
    private readonly RequestPipeline _pipeline;

    internal HelpdeskTicketResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>创建工单（POST /open-apis/helpdesk/v1/tickets）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/helpdesk/v1/tickets",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        options = (options ?? RequestOptions.Default).WithHelpdeskAuth();
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>查询指定工单详情（GET /open-apis/helpdesk/v1/tickets/:ticket_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string ticketid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/helpdesk/v1/tickets/:ticket_id",
            PathParams =
            {
                ["ticket_id"] = ticketid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        options = (options ?? RequestOptions.Default).WithHelpdeskAuth();
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>查询全部工单详情（GET /open-apis/helpdesk/v1/tickets）。</summary>
    public Task<FeishuDataResponse> ListAsync(IDictionary<string, string>? query = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/helpdesk/v1/tickets",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        options = (options ?? RequestOptions.Default).WithHelpdeskAuth();
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>查询全部工单详情：自动翻页枚举 data.items。</summary>
    public async IAsyncEnumerable<System.Text.Json.JsonElement> ListAsyncEnumerate(IDictionary<string, string>? query = null, RequestOptions? options = null, int? limit = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var emitted = 0;
        string? pageToken = null;
        do
        {
            var pageQuery = query == null ? new Dictionary<string, string>() : new Dictionary<string, string>(query);
            if (pageToken != null) pageQuery["page_token"] = pageToken;
            var page = await ListAsync(pageQuery, options, cancellationToken);
            page.EnsureSuccess();
            if (page.Data is not { ValueKind: System.Text.Json.JsonValueKind.Object } data) yield break;
            if (!data.TryGetProperty("items", out var items) || items.ValueKind != System.Text.Json.JsonValueKind.Array) yield break;
            foreach (var item in items.EnumerateArray())
            {
                if (limit.HasValue && emitted >= limit.Value) yield break;
                emitted++;
                yield return item;
            }
            pageToken = page.PageToken is { Length: > 0 } ? page.PageToken : null;
        } while (pageToken != null);
    }

    /// <summary>创建服务台对话（POST /open-apis/helpdesk/v1/start_service）。</summary>
    public Task<FeishuDataResponse> StartServiceAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/helpdesk/v1/start_service",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>回复用户在工单里的提问（POST /open-apis/helpdesk/v1/tickets/:ticket_id/answer_user_query）。</summary>
    public Task<FeishuDataResponse> AnswerUserQueryAsync(string ticketid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/helpdesk/v1/tickets/:ticket_id/answer_user_query",
            PathParams =
            {
                ["ticket_id"] = ticketid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取服务台自定义字段（GET /open-apis/helpdesk/v1/customized_fields）。</summary>
    public Task<FeishuDataResponse> CustomizedFieldsAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/helpdesk/v1/customized_fields",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class HelpdeskTicketMessageResource
{
    private readonly RequestPipeline _pipeline;

    internal HelpdeskTicketMessageResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>获取工单消息列表（GET /open-apis/helpdesk/v1/tickets/:ticket_id/messages）。</summary>
    public Task<FeishuDataResponse> ListAsync(string ticketid, IDictionary<string, string>? query = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/helpdesk/v1/tickets/:ticket_id/messages",
            PathParams =
            {
                ["ticket_id"] = ticketid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        options = (options ?? RequestOptions.Default).WithHelpdeskAuth();
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取工单消息列表：自动翻页枚举 data.items。</summary>
    public async IAsyncEnumerable<System.Text.Json.JsonElement> ListAsyncEnumerate(string ticketid, IDictionary<string, string>? query = null, RequestOptions? options = null, int? limit = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var emitted = 0;
        string? pageToken = null;
        do
        {
            var pageQuery = query == null ? new Dictionary<string, string>() : new Dictionary<string, string>(query);
            if (pageToken != null) pageQuery["page_token"] = pageToken;
            var page = await ListAsync(ticketid, pageQuery, options, cancellationToken);
            page.EnsureSuccess();
            if (page.Data is not { ValueKind: System.Text.Json.JsonValueKind.Object } data) yield break;
            if (!data.TryGetProperty("items", out var items) || items.ValueKind != System.Text.Json.JsonValueKind.Array) yield break;
            foreach (var item in items.EnumerateArray())
            {
                if (limit.HasValue && emitted >= limit.Value) yield break;
                emitted++;
                yield return item;
            }
            pageToken = page.PageToken is { Length: > 0 } ? page.PageToken : null;
        } while (pageToken != null);
    }

    /// <summary>回复工单消息（POST /open-apis/helpdesk/v1/tickets/:ticket_id/messages）。</summary>
    public Task<FeishuDataResponse> CreateAsync(string ticketid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/helpdesk/v1/tickets/:ticket_id/messages",
            PathParams =
            {
                ["ticket_id"] = ticketid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        options = (options ?? RequestOptions.Default).WithHelpdeskAuth();
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

}
