// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.Lingo;

/// <summary>飞书词典（lingo/v1）（生成代码：14 个端点）。</summary>
public sealed class LingoService
{
    private readonly RequestPipeline _pipeline;

    internal LingoService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        Classification = new LingoClassificationResource(pipeline);
        Draft = new LingoDraftResource(pipeline);
        Entity = new LingoEntityResource(pipeline);
        File = new LingoFileResource(pipeline);
        Repo = new LingoRepoResource(pipeline);
    }

    /// <summary>Classification 资源。</summary>
    public LingoClassificationResource Classification { get; }
    /// <summary>Draft 资源。</summary>
    public LingoDraftResource Draft { get; }
    /// <summary>Entity 资源。</summary>
    public LingoEntityResource Entity { get; }
    /// <summary>File 资源。</summary>
    public LingoFileResource File { get; }
    /// <summary>Repo 资源。</summary>
    public LingoRepoResource Repo { get; }

public sealed class LingoClassificationResource
{
    private readonly RequestPipeline _pipeline;

    internal LingoClassificationResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>获取词典分类（GET /open-apis/lingo/v1/classifications）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/lingo/v1/classifications",
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class LingoDraftResource
{
    private readonly RequestPipeline _pipeline;

    internal LingoDraftResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>创建草稿（POST /open-apis/lingo/v1/drafts）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/lingo/v1/drafts",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>更新草稿（PUT /open-apis/lingo/v1/drafts/:draft_id）。</summary>
    public Task<FeishuDataResponse> UpdateAsync(string draftid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Put,
            Path = "/open-apis/lingo/v1/drafts/:draft_id",
            PathParams =
            {
                ["draft_id"] = draftid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class LingoEntityResource
{
    private readonly RequestPipeline _pipeline;

    internal LingoEntityResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>创建免审词条（POST /open-apis/lingo/v1/entities）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/lingo/v1/entities",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取词条详情（GET /open-apis/lingo/v1/entities/:entity_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string entityid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/lingo/v1/entities/:entity_id",
            PathParams =
            {
                ["entity_id"] = entityid,
            },
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>更新免审词条（PUT /open-apis/lingo/v1/entities/:entity_id）。</summary>
    public Task<FeishuDataResponse> UpdateAsync(string entityid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Put,
            Path = "/open-apis/lingo/v1/entities/:entity_id",
            PathParams =
            {
                ["entity_id"] = entityid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>删除免审词条（DELETE /open-apis/lingo/v1/entities/:entity_id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string entityid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/lingo/v1/entities/:entity_id",
            PathParams =
            {
                ["entity_id"] = entityid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取词条列表（GET /open-apis/lingo/v1/entities）。</summary>
    public Task<FeishuDataResponse> ListAsync(IDictionary<string, string>? query = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/lingo/v1/entities",
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取词条列表：自动翻页枚举 data.items。</summary>
    public async IAsyncEnumerable<System.Text.Json.JsonElement> ListAsyncEnumerate(IDictionary<string, string>? query = null, RequestOptions? options = null, int? limit = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var emitted = 0;
        string? pageToken = null;
        do
        {
            var pageQuery = query == null ? new Dictionary<string, string>() : new Dictionary<string, string>(query);
            if (pageToken != null) pageQuery["page_token"] = pageToken;
            var page = await ListAsync(pageQuery, options, cancellationToken);
            page.EnsureSuccess();
            if (page.Data is not { ValueKind: System.Text.Json.JsonValueKind.Object } data) yield break;
            if (!data.TryGetProperty("items", out var items) || items.ValueKind != System.Text.Json.JsonValueKind.Array) yield break;
            foreach (var item in items.EnumerateArray())
            {
                if (limit.HasValue && emitted >= limit.Value) yield break;
                emitted++;
                yield return item;
            }
            pageToken = page.PageToken is { Length: > 0 } ? page.PageToken : null;
        } while (pageToken != null);
    }

    /// <summary>模糊搜索词条（POST /open-apis/lingo/v1/entities/search）。</summary>
    public Task<FeishuDataResponse> SearchAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/lingo/v1/entities/search",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>精准搜索词条（POST /open-apis/lingo/v1/entities/match）。</summary>
    public Task<FeishuDataResponse> MatchAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/lingo/v1/entities/match",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>词条高亮（POST /open-apis/lingo/v1/entities/highlight）。</summary>
    public Task<FeishuDataResponse> HighlightAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/lingo/v1/entities/highlight",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class LingoFileResource
{
    private readonly RequestPipeline _pipeline;

    internal LingoFileResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>上传图片（POST /open-apis/lingo/v1/files/upload）。</summary>
    public Task<FeishuDataResponse> UploadAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/lingo/v1/files/upload",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>下载图片（GET /open-apis/lingo/v1/files/:file_token/download）。</summary>
    public Task<ApiResponse> DownloadAsync(string filetoken, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/lingo/v1/files/:file_token/download",
            PathParams =
            {
                ["file_token"] = filetoken,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        options = (options ?? RequestOptions.Default).WithFileDownload();
        return _pipeline.SendAsync(api, options, cancellationToken);
    }

}

public sealed class LingoRepoResource
{
    private readonly RequestPipeline _pipeline;

    internal LingoRepoResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>获取词库列表（GET /open-apis/lingo/v1/repos）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/lingo/v1/repos",
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

}
