// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.Bot;

/// <summary>机器人（bot/v3）（生成代码：1 个端点）。</summary>
public sealed class BotService
{
    private readonly RequestPipeline _pipeline;

    internal BotService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        Bot = new BotBotResource(pipeline);
    }

    /// <summary>Bot 资源。</summary>
    public BotBotResource Bot { get; }

public sealed class BotBotResource
{
    private readonly RequestPipeline _pipeline;

    internal BotBotResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>获取机器人信息（GET /open-apis/bot/v3/info）。</summary>
    public Task<FeishuDataResponse> GetInfoAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/bot/v3/info",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

}
