// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.Verification;

/// <summary>企业认证信息（verification/v1）（生成代码：1 个端点）。</summary>
public sealed class VerificationService
{
    private readonly RequestPipeline _pipeline;

    internal VerificationService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        Verification = new VerificationVerificationResource(pipeline);
    }

    /// <summary>Verification 资源。</summary>
    public VerificationVerificationResource Verification { get; }

public sealed class VerificationVerificationResource
{
    private readonly RequestPipeline _pipeline;

    internal VerificationVerificationResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>获取认证信息（GET /open-apis/verification/v1/verification）。</summary>
    public Task<FeishuDataResponse> GetAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/verification/v1/verification",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

}
