// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.Search;

/// <summary>搜索（suite/docs-api）（生成代码：1 个端点）。</summary>
public sealed class SearchService
{
    private readonly RequestPipeline _pipeline;

    internal SearchService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        DocsSearch = new SearchDocsSearchResource(pipeline);
    }

    /// <summary>DocsSearch 资源。</summary>
    public SearchDocsSearchResource DocsSearch { get; }

public sealed class SearchDocsSearchResource
{
    private readonly RequestPipeline _pipeline;

    internal SearchDocsSearchResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>搜索文档（POST /open-apis/suite/docs-api/search/object）。</summary>
    public Task<FeishuDataResponse> SearchAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/suite/docs-api/search/object",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

}
