// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.Attendance;

/// <summary>考勤（attendance/v1）（生成代码：36 个端点）。</summary>
public sealed class AttendanceService
{
    private readonly RequestPipeline _pipeline;

    internal AttendanceService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        ApprovalInfo = new AttendanceApprovalInfoResource(pipeline);
        ArchiveRule = new AttendanceArchiveRuleResource(pipeline);
        File = new AttendanceFileResource(pipeline);
        Group = new AttendanceGroupResource(pipeline);
        LeaveAccrualRecord = new AttendanceLeaveAccrualRecordResource(pipeline);
        LeaveEmployExpireRecord = new AttendanceLeaveEmployExpireRecordResource(pipeline);
        Shift = new AttendanceShiftResource(pipeline);
        UserApproval = new AttendanceUserApprovalResource(pipeline);
        UserDailyShift = new AttendanceUserDailyShiftResource(pipeline);
        UserFlow = new AttendanceUserFlowResource(pipeline);
        UserSetting = new AttendanceUserSettingResource(pipeline);
        UserStatsData = new AttendanceUserStatsDataResource(pipeline);
        UserStatsField = new AttendanceUserStatsFieldResource(pipeline);
        UserStatsView = new AttendanceUserStatsViewResource(pipeline);
        UserTask = new AttendanceUserTaskResource(pipeline);
        UserTaskRemedy = new AttendanceUserTaskRemedyResource(pipeline);
    }

    /// <summary>ApprovalInfo 资源。</summary>
    public AttendanceApprovalInfoResource ApprovalInfo { get; }
    /// <summary>ArchiveRule 资源。</summary>
    public AttendanceArchiveRuleResource ArchiveRule { get; }
    /// <summary>File 资源。</summary>
    public AttendanceFileResource File { get; }
    /// <summary>Group 资源。</summary>
    public AttendanceGroupResource Group { get; }
    /// <summary>LeaveAccrualRecord 资源。</summary>
    public AttendanceLeaveAccrualRecordResource LeaveAccrualRecord { get; }
    /// <summary>LeaveEmployExpireRecord 资源。</summary>
    public AttendanceLeaveEmployExpireRecordResource LeaveEmployExpireRecord { get; }
    /// <summary>Shift 资源。</summary>
    public AttendanceShiftResource Shift { get; }
    /// <summary>UserApproval 资源。</summary>
    public AttendanceUserApprovalResource UserApproval { get; }
    /// <summary>UserDailyShift 资源。</summary>
    public AttendanceUserDailyShiftResource UserDailyShift { get; }
    /// <summary>UserFlow 资源。</summary>
    public AttendanceUserFlowResource UserFlow { get; }
    /// <summary>UserSetting 资源。</summary>
    public AttendanceUserSettingResource UserSetting { get; }
    /// <summary>UserStatsData 资源。</summary>
    public AttendanceUserStatsDataResource UserStatsData { get; }
    /// <summary>UserStatsField 资源。</summary>
    public AttendanceUserStatsFieldResource UserStatsField { get; }
    /// <summary>UserStatsView 资源。</summary>
    public AttendanceUserStatsViewResource UserStatsView { get; }
    /// <summary>UserTask 资源。</summary>
    public AttendanceUserTaskResource UserTask { get; }
    /// <summary>UserTaskRemedy 资源。</summary>
    public AttendanceUserTaskRemedyResource UserTaskRemedy { get; }

public sealed class AttendanceApprovalInfoResource
{
    private readonly RequestPipeline _pipeline;

    internal AttendanceApprovalInfoResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>通知审批状态更新（POST /open-apis/attendance/v1/approval_infos/process）。</summary>
    public Task<FeishuDataResponse> ProcessAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/attendance/v1/approval_infos/process",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class AttendanceArchiveRuleResource
{
    private readonly RequestPipeline _pipeline;

    internal AttendanceArchiveRuleResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>查询所有归档规则（GET /open-apis/attendance/v1/archive_rule）。</summary>
    public Task<FeishuDataResponse> ListAsync(IDictionary<string, string>? query = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/attendance/v1/archive_rule",
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>查询所有归档规则：自动翻页枚举 data.items。</summary>
    public async IAsyncEnumerable<System.Text.Json.JsonElement> ListAsyncEnumerate(IDictionary<string, string>? query = null, RequestOptions? options = null, int? limit = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var emitted = 0;
        string? pageToken = null;
        do
        {
            var pageQuery = query == null ? new Dictionary<string, string>() : new Dictionary<string, string>(query);
            if (pageToken != null) pageQuery["page_token"] = pageToken;
            var page = await ListAsync(pageQuery, options, cancellationToken);
            page.EnsureSuccess();
            if (page.Data is not { ValueKind: System.Text.Json.JsonValueKind.Object } data) yield break;
            if (!data.TryGetProperty("items", out var items) || items.ValueKind != System.Text.Json.JsonValueKind.Array) yield break;
            foreach (var item in items.EnumerateArray())
            {
                if (limit.HasValue && emitted >= limit.Value) yield break;
                emitted++;
                yield return item;
            }
            pageToken = page.PageToken is { Length: > 0 } ? page.PageToken : null;
        } while (pageToken != null);
    }

    /// <summary>删除归档报表行数据（POST /open-apis/attendance/v1/archive_rule/del_report）。</summary>
    public Task<FeishuDataResponse> DelReportAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/attendance/v1/archive_rule/del_report",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>写入归档报表结果（POST /open-apis/attendance/v1/archive_rule/upload_report）。</summary>
    public Task<FeishuDataResponse> UploadReportAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/attendance/v1/archive_rule/upload_report",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>查询归档报表表头（POST /open-apis/attendance/v1/archive_rule/user_stats_fields_query）。</summary>
    public Task<FeishuDataResponse> UserStatsFieldsQueryAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/attendance/v1/archive_rule/user_stats_fields_query",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class AttendanceFileResource
{
    private readonly RequestPipeline _pipeline;

    internal AttendanceFileResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>上传用户人脸识别照片（POST /open-apis/attendance/v1/files/upload）。</summary>
    public Task<FeishuDataResponse> UploadAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/attendance/v1/files/upload",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>下载用户人脸识别照片（GET /open-apis/attendance/v1/files/:file_id/download）。</summary>
    public Task<ApiResponse> DownloadAsync(string fileid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/attendance/v1/files/:file_id/download",
            PathParams =
            {
                ["file_id"] = fileid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        options = (options ?? RequestOptions.Default).WithFileDownload();
        return _pipeline.SendAsync(api, options, cancellationToken);
    }

}

public sealed class AttendanceGroupResource
{
    private readonly RequestPipeline _pipeline;

    internal AttendanceGroupResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>创建或修改考勤组（POST /open-apis/attendance/v1/groups）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/attendance/v1/groups",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>按 ID 查询考勤组（GET /open-apis/attendance/v1/groups/:group_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string groupid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/attendance/v1/groups/:group_id",
            PathParams =
            {
                ["group_id"] = groupid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>删除考勤组（DELETE /open-apis/attendance/v1/groups/:group_id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string groupid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/attendance/v1/groups/:group_id",
            PathParams =
            {
                ["group_id"] = groupid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>查询所有考勤组（GET /open-apis/attendance/v1/groups）。</summary>
    public Task<FeishuDataResponse> ListAsync(IDictionary<string, string>? query = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/attendance/v1/groups",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>查询所有考勤组：自动翻页枚举 data.items。</summary>
    public async IAsyncEnumerable<System.Text.Json.JsonElement> ListAsyncEnumerate(IDictionary<string, string>? query = null, RequestOptions? options = null, int? limit = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var emitted = 0;
        string? pageToken = null;
        do
        {
            var pageQuery = query == null ? new Dictionary<string, string>() : new Dictionary<string, string>(query);
            if (pageToken != null) pageQuery["page_token"] = pageToken;
            var page = await ListAsync(pageQuery, options, cancellationToken);
            page.EnsureSuccess();
            if (page.Data is not { ValueKind: System.Text.Json.JsonValueKind.Object } data) yield break;
            if (!data.TryGetProperty("items", out var items) || items.ValueKind != System.Text.Json.JsonValueKind.Array) yield break;
            foreach (var item in items.EnumerateArray())
            {
                if (limit.HasValue && emitted >= limit.Value) yield break;
                emitted++;
                yield return item;
            }
            pageToken = page.PageToken is { Length: > 0 } ? page.PageToken : null;
        } while (pageToken != null);
    }

    /// <summary>查询考勤组下所有成员（GET /open-apis/attendance/v1/groups/:group_id/list_user）。</summary>
    public Task<FeishuDataResponse> ListUserAsync(string groupid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/attendance/v1/groups/:group_id/list_user",
            PathParams =
            {
                ["group_id"] = groupid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>按名称查询考勤组（POST /open-apis/attendance/v1/groups/search）。</summary>
    public Task<FeishuDataResponse> SearchAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/attendance/v1/groups/search",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class AttendanceLeaveAccrualRecordResource
{
    private readonly RequestPipeline _pipeline;

    internal AttendanceLeaveAccrualRecordResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>修改发放记录（PATCH /open-apis/attendance/v1/leave_accrual_record/:leave_id）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string leaveid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/attendance/v1/leave_accrual_record/:leave_id",
            PathParams =
            {
                ["leave_id"] = leaveid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class AttendanceLeaveEmployExpireRecordResource
{
    private readonly RequestPipeline _pipeline;

    internal AttendanceLeaveEmployExpireRecordResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>通过过期时间获取发放记录（GET /open-apis/attendance/v1/leave_employ_expire_records/:leave_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string leaveid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/attendance/v1/leave_employ_expire_records/:leave_id",
            PathParams =
            {
                ["leave_id"] = leaveid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class AttendanceShiftResource
{
    private readonly RequestPipeline _pipeline;

    internal AttendanceShiftResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>创建班次（POST /open-apis/attendance/v1/shifts）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/attendance/v1/shifts",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>查询班次（GET /open-apis/attendance/v1/shifts/:shift_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string shiftid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/attendance/v1/shifts/:shift_id",
            PathParams =
            {
                ["shift_id"] = shiftid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>删除班次（DELETE /open-apis/attendance/v1/shifts/:shift_id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string shiftid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/attendance/v1/shifts/:shift_id",
            PathParams =
            {
                ["shift_id"] = shiftid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>查询所有班次（GET /open-apis/attendance/v1/shifts）。</summary>
    public Task<FeishuDataResponse> ListAsync(IDictionary<string, string>? query = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/attendance/v1/shifts",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>查询所有班次：自动翻页枚举 data.items。</summary>
    public async IAsyncEnumerable<System.Text.Json.JsonElement> ListAsyncEnumerate(IDictionary<string, string>? query = null, RequestOptions? options = null, int? limit = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var emitted = 0;
        string? pageToken = null;
        do
        {
            var pageQuery = query == null ? new Dictionary<string, string>() : new Dictionary<string, string>(query);
            if (pageToken != null) pageQuery["page_token"] = pageToken;
            var page = await ListAsync(pageQuery, options, cancellationToken);
            page.EnsureSuccess();
            if (page.Data is not { ValueKind: System.Text.Json.JsonValueKind.Object } data) yield break;
            if (!data.TryGetProperty("items", out var items) || items.ValueKind != System.Text.Json.JsonValueKind.Array) yield break;
            foreach (var item in items.EnumerateArray())
            {
                if (limit.HasValue && emitted >= limit.Value) yield break;
                emitted++;
                yield return item;
            }
            pageToken = page.PageToken is { Length: > 0 } ? page.PageToken : null;
        } while (pageToken != null);
    }

    /// <summary>按名称查询班次（POST /open-apis/attendance/v1/shifts/query）。</summary>
    public Task<FeishuDataResponse> QueryAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/attendance/v1/shifts/query",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class AttendanceUserApprovalResource
{
    private readonly RequestPipeline _pipeline;

    internal AttendanceUserApprovalResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>写入审批结果（POST /open-apis/attendance/v1/user_approvals）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/attendance/v1/user_approvals",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取审批通过数据（POST /open-apis/attendance/v1/user_approvals/query）。</summary>
    public Task<FeishuDataResponse> QueryAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/attendance/v1/user_approvals/query",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class AttendanceUserDailyShiftResource
{
    private readonly RequestPipeline _pipeline;

    internal AttendanceUserDailyShiftResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>创建或修改排班表（POST /open-apis/attendance/v1/user_daily_shifts/batch_create）。</summary>
    public Task<FeishuDataResponse> BatchCreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/attendance/v1/user_daily_shifts/batch_create",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>创建或更改临时排班（POST /open-apis/attendance/v1/user_daily_shifts/batch_create_temp）。</summary>
    public Task<FeishuDataResponse> BatchCreateTempAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/attendance/v1/user_daily_shifts/batch_create_temp",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>查询班表信息（POST /open-apis/attendance/v1/user_daily_shifts/query）。</summary>
    public Task<FeishuDataResponse> QueryAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/attendance/v1/user_daily_shifts/query",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class AttendanceUserFlowResource
{
    private readonly RequestPipeline _pipeline;

    internal AttendanceUserFlowResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>导入打卡流水（POST /open-apis/attendance/v1/user_flows/batch_create）。</summary>
    public Task<FeishuDataResponse> BatchCreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/attendance/v1/user_flows/batch_create",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>删除打卡流水（POST /open-apis/attendance/v1/user_flows/batch_del）。</summary>
    public Task<FeishuDataResponse> BatchDelAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/attendance/v1/user_flows/batch_del",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>查询打卡流水（GET /open-apis/attendance/v1/user_flows/:user_flow_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string userflowid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/attendance/v1/user_flows/:user_flow_id",
            PathParams =
            {
                ["user_flow_id"] = userflowid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>批量查询打卡流水（POST /open-apis/attendance/v1/user_flows/query）。</summary>
    public Task<FeishuDataResponse> QueryAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/attendance/v1/user_flows/query",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class AttendanceUserSettingResource
{
    private readonly RequestPipeline _pipeline;

    internal AttendanceUserSettingResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>修改用户人脸识别信息（POST /open-apis/attendance/v1/user_settings/modify）。</summary>
    public Task<FeishuDataResponse> ModifyAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/attendance/v1/user_settings/modify",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>批量查询用户人脸识别信息（GET /open-apis/attendance/v1/user_settings/query）。</summary>
    public Task<FeishuDataResponse> QueryAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/attendance/v1/user_settings/query",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class AttendanceUserStatsDataResource
{
    private readonly RequestPipeline _pipeline;

    internal AttendanceUserStatsDataResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>查询统计数据（POST /open-apis/attendance/v1/user_stats_datas/query）。</summary>
    public Task<FeishuDataResponse> QueryAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/attendance/v1/user_stats_datas/query",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class AttendanceUserStatsFieldResource
{
    private readonly RequestPipeline _pipeline;

    internal AttendanceUserStatsFieldResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>查询统计表头（POST /open-apis/attendance/v1/user_stats_fields/query）。</summary>
    public Task<FeishuDataResponse> QueryAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/attendance/v1/user_stats_fields/query",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class AttendanceUserStatsViewResource
{
    private readonly RequestPipeline _pipeline;

    internal AttendanceUserStatsViewResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>查询统计设置（历史视图模型）（POST /open-apis/attendance/v1/user_stats_views/query）。</summary>
    public Task<FeishuDataResponse> QueryAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/attendance/v1/user_stats_views/query",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class AttendanceUserTaskResource
{
    private readonly RequestPipeline _pipeline;

    internal AttendanceUserTaskResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>查询打卡结果（POST /open-apis/attendance/v1/user_tasks/query）。</summary>
    public Task<FeishuDataResponse> QueryAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/attendance/v1/user_tasks/query",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class AttendanceUserTaskRemedyResource
{
    private readonly RequestPipeline _pipeline;

    internal AttendanceUserTaskRemedyResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>补卡（POST /open-apis/attendance/v1/user_task_remedies）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/attendance/v1/user_task_remedies",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

}
