// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.Approval;

/// <summary>审批（approval/v4 高频端点）（生成代码：7 个端点）。</summary>
public sealed class ApprovalService
{
    private readonly RequestPipeline _pipeline;

    internal ApprovalService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        Approval = new ApprovalApprovalResource(pipeline);
        Instance = new ApprovalInstanceResource(pipeline);
    }

    /// <summary>Approval 资源。</summary>
    public ApprovalApprovalResource Approval { get; }
    /// <summary>Instance 资源。</summary>
    public ApprovalInstanceResource Instance { get; }

public sealed class ApprovalApprovalResource
{
    private readonly RequestPipeline _pipeline;

    internal ApprovalApprovalResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>创建审批定义（POST /open-apis/approval/v4/approvals）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/approval/v4/approvals",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>查看指定审批定义（GET /open-apis/approval/v4/approvals/:approval_code）。</summary>
    public Task<FeishuDataResponse> GetAsync(string approvalcode, IDictionary<string, string>? query = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/approval/v4/approvals/:approval_code",
            PathParams =
            {
                ["approval_code"] = approvalcode,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>订阅审批事件（POST /open-apis/approval/v4/approvals/:approval_code/subscribe）。</summary>
    public Task<FeishuDataResponse> SubscribeAsync(string approvalcode, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/approval/v4/approvals/:approval_code/subscribe",
            PathParams =
            {
                ["approval_code"] = approvalcode,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class ApprovalInstanceResource
{
    private readonly RequestPipeline _pipeline;

    internal ApprovalInstanceResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>创建审批实例（POST /open-apis/approval/v4/instances）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/approval/v4/instances",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>查询单个审批实例详情（GET /open-apis/approval/v4/instances/:instance_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string instanceid, IDictionary<string, string>? query = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/approval/v4/instances/:instance_id",
            PathParams =
            {
                ["instance_id"] = instanceid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>同意审批任务（POST /open-apis/approval/v4/instances/approve）。</summary>
    public Task<FeishuDataResponse> ApproveAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/approval/v4/instances/approve",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>拒绝审批任务（POST /open-apis/approval/v4/instances/reject）。</summary>
    public Task<FeishuDataResponse> RejectAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/approval/v4/instances/reject",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

}
