// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.Mdm;

/// <summary>主数据管理（mdm v1 绑定关系 + v3 国家地区）（生成代码：4 个端点）。</summary>
public sealed class MdmService
{
    private readonly RequestPipeline _pipeline;

    internal MdmService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        UserAuthDataRelation = new MdmUserAuthDataRelationResource(pipeline);
        BatchCountryRegion = new MdmBatchCountryRegionResource(pipeline);
        CountryRegion = new MdmCountryRegionResource(pipeline);
    }

    /// <summary>UserAuthDataRelation 资源。</summary>
    public MdmUserAuthDataRelationResource UserAuthDataRelation { get; }
    /// <summary>BatchCountryRegion 资源。</summary>
    public MdmBatchCountryRegionResource BatchCountryRegion { get; }
    /// <summary>CountryRegion 资源。</summary>
    public MdmCountryRegionResource CountryRegion { get; }

public sealed class MdmUserAuthDataRelationResource
{
    private readonly RequestPipeline _pipeline;

    internal MdmUserAuthDataRelationResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>用户数据维度绑定（POST /open-apis/mdm/v1/user_auth_data_relations/bind）。</summary>
    public Task<FeishuDataResponse> BindAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/mdm/v1/user_auth_data_relations/bind",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>用户数据维度解绑（POST /open-apis/mdm/v1/user_auth_data_relations/unbind）。</summary>
    public Task<FeishuDataResponse> UnbindAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/mdm/v1/user_auth_data_relations/unbind",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class MdmBatchCountryRegionResource
{
    private readonly RequestPipeline _pipeline;

    internal MdmBatchCountryRegionResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>按 mdmcode 批量查询国家/地区（GET /open-apis/mdm/v3/batch_country_region）。</summary>
    public Task<FeishuDataResponse> GetAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/mdm/v3/batch_country_region",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class MdmCountryRegionResource
{
    private readonly RequestPipeline _pipeline;

    internal MdmCountryRegionResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>分页查询国家/地区（GET /open-apis/mdm/v3/country_regions）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/mdm/v3/country_regions",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

}
