// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.Corehr;

/// <summary>飞书人事企业版（corehr/v1 全量，机读提取）（生成代码：105 个端点）。</summary>
public sealed class CorehrService
{
    private readonly RequestPipeline _pipeline;

    internal CorehrService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        AssignedUser = new CorehrAssignedUserResource(pipeline);
        Authorization = new CorehrAuthorizationResource(pipeline);
        CommonDataId = new CorehrCommonDataIdResource(pipeline);
        CommonDataMetaData = new CorehrCommonDataMetaDataResource(pipeline);
        Company = new CorehrCompanyResource(pipeline);
        CompensationStandard = new CorehrCompensationStandardResource(pipeline);
        Contract = new CorehrContractResource(pipeline);
        CountryRegion = new CorehrCountryRegionResource(pipeline);
        Currency = new CorehrCurrencyResource(pipeline);
        CustomField = new CorehrCustomFieldResource(pipeline);
        Department = new CorehrDepartmentResource(pipeline);
        EmployeeType = new CorehrEmployeeTypeResource(pipeline);
        Employment = new CorehrEmploymentResource(pipeline);
        File = new CorehrFileResource(pipeline);
        Job = new CorehrJobResource(pipeline);
        JobChange = new CorehrJobChangeResource(pipeline);
        JobData = new CorehrJobDataResource(pipeline);
        JobFamily = new CorehrJobFamilyResource(pipeline);
        JobLevel = new CorehrJobLevelResource(pipeline);
        Leave = new CorehrLeaveResource(pipeline);
        LeaveGrantingRecord = new CorehrLeaveGrantingRecordResource(pipeline);
        Location = new CorehrLocationResource(pipeline);
        NationalIdType = new CorehrNationalIdTypeResource(pipeline);
        Offboarding = new CorehrOffboardingResource(pipeline);
        Person = new CorehrPersonResource(pipeline);
        PreHire = new CorehrPreHireResource(pipeline);
        ProcessFormVariableData = new CorehrProcessFormVariableDataResource(pipeline);
        SecurityGroup = new CorehrSecurityGroupResource(pipeline);
        Subdivision = new CorehrSubdivisionResource(pipeline);
        Subregion = new CorehrSubregionResource(pipeline);
        TransferReason = new CorehrTransferReasonResource(pipeline);
        TransferType = new CorehrTransferTypeResource(pipeline);
        WorkingHoursType = new CorehrWorkingHoursTypeResource(pipeline);
    }

    /// <summary>AssignedUser 资源。</summary>
    public CorehrAssignedUserResource AssignedUser { get; }
    /// <summary>Authorization 资源。</summary>
    public CorehrAuthorizationResource Authorization { get; }
    /// <summary>CommonDataId 资源。</summary>
    public CorehrCommonDataIdResource CommonDataId { get; }
    /// <summary>CommonDataMetaData 资源。</summary>
    public CorehrCommonDataMetaDataResource CommonDataMetaData { get; }
    /// <summary>Company 资源。</summary>
    public CorehrCompanyResource Company { get; }
    /// <summary>CompensationStandard 资源。</summary>
    public CorehrCompensationStandardResource CompensationStandard { get; }
    /// <summary>Contract 资源。</summary>
    public CorehrContractResource Contract { get; }
    /// <summary>CountryRegion 资源。</summary>
    public CorehrCountryRegionResource CountryRegion { get; }
    /// <summary>Currency 资源。</summary>
    public CorehrCurrencyResource Currency { get; }
    /// <summary>CustomField 资源。</summary>
    public CorehrCustomFieldResource CustomField { get; }
    /// <summary>Department 资源。</summary>
    public CorehrDepartmentResource Department { get; }
    /// <summary>EmployeeType 资源。</summary>
    public CorehrEmployeeTypeResource EmployeeType { get; }
    /// <summary>Employment 资源。</summary>
    public CorehrEmploymentResource Employment { get; }
    /// <summary>File 资源。</summary>
    public CorehrFileResource File { get; }
    /// <summary>Job 资源。</summary>
    public CorehrJobResource Job { get; }
    /// <summary>JobChange 资源。</summary>
    public CorehrJobChangeResource JobChange { get; }
    /// <summary>JobData 资源。</summary>
    public CorehrJobDataResource JobData { get; }
    /// <summary>JobFamily 资源。</summary>
    public CorehrJobFamilyResource JobFamily { get; }
    /// <summary>JobLevel 资源。</summary>
    public CorehrJobLevelResource JobLevel { get; }
    /// <summary>Leave 资源。</summary>
    public CorehrLeaveResource Leave { get; }
    /// <summary>LeaveGrantingRecord 资源。</summary>
    public CorehrLeaveGrantingRecordResource LeaveGrantingRecord { get; }
    /// <summary>Location 资源。</summary>
    public CorehrLocationResource Location { get; }
    /// <summary>NationalIdType 资源。</summary>
    public CorehrNationalIdTypeResource NationalIdType { get; }
    /// <summary>Offboarding 资源。</summary>
    public CorehrOffboardingResource Offboarding { get; }
    /// <summary>Person 资源。</summary>
    public CorehrPersonResource Person { get; }
    /// <summary>PreHire 资源。</summary>
    public CorehrPreHireResource PreHire { get; }
    /// <summary>ProcessFormVariableData 资源。</summary>
    public CorehrProcessFormVariableDataResource ProcessFormVariableData { get; }
    /// <summary>SecurityGroup 资源。</summary>
    public CorehrSecurityGroupResource SecurityGroup { get; }
    /// <summary>Subdivision 资源。</summary>
    public CorehrSubdivisionResource Subdivision { get; }
    /// <summary>Subregion 资源。</summary>
    public CorehrSubregionResource Subregion { get; }
    /// <summary>TransferReason 资源。</summary>
    public CorehrTransferReasonResource TransferReason { get; }
    /// <summary>TransferType 资源。</summary>
    public CorehrTransferTypeResource TransferType { get; }
    /// <summary>WorkingHoursType 资源。</summary>
    public CorehrWorkingHoursTypeResource WorkingHoursType { get; }

public sealed class CorehrAssignedUserResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrAssignedUserResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Search /open-apis/corehr/v1/assigned_users/search（Post /open-apis/corehr/v1/assigned_users/search）。</summary>
    public Task<FeishuDataResponse> SearchAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/corehr/v1/assigned_users/search",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrAuthorizationResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrAuthorizationResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>AddRoleAssign /open-apis/corehr/v1/authorizations/add_role_assign（Post /open-apis/corehr/v1/authorizations/add_role_assign）。</summary>
    public Task<FeishuDataResponse> AddRoleAssignAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/corehr/v1/authorizations/add_role_assign",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>GetByParam /open-apis/corehr/v1/authorizations/get_by_param（Get /open-apis/corehr/v1/authorizations/get_by_param）。</summary>
    public Task<FeishuDataResponse> GetByParamAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/authorizations/get_by_param",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Query /open-apis/corehr/v1/authorizations/query（Get /open-apis/corehr/v1/authorizations/query）。</summary>
    public Task<FeishuDataResponse> QueryAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/authorizations/query",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>RemoveRoleAssign /open-apis/corehr/v1/authorizations/remove_role_assign（Post /open-apis/corehr/v1/authorizations/remove_role_assign）。</summary>
    public Task<FeishuDataResponse> RemoveRoleAssignAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/corehr/v1/authorizations/remove_role_assign",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>UpdateRoleAssign /open-apis/corehr/v1/authorizations/update_role_assign（Post /open-apis/corehr/v1/authorizations/update_role_assign）。</summary>
    public Task<FeishuDataResponse> UpdateRoleAssignAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/corehr/v1/authorizations/update_role_assign",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrCommonDataIdResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrCommonDataIdResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Convert /open-apis/corehr/v1/common_data/id/convert（Post /open-apis/corehr/v1/common_data/id/convert）。</summary>
    public Task<FeishuDataResponse> ConvertAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/corehr/v1/common_data/id/convert",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrCommonDataMetaDataResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrCommonDataMetaDataResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>AddEnumOption /open-apis/corehr/v1/common_data/meta_data/add_enum_option（Post /open-apis/corehr/v1/common_data/meta_data/add_enum_option）。</summary>
    public Task<FeishuDataResponse> AddEnumOptionAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/corehr/v1/common_data/meta_data/add_enum_option",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>EditEnumOption /open-apis/corehr/v1/common_data/meta_data/edit_enum_option（Post /open-apis/corehr/v1/common_data/meta_data/edit_enum_option）。</summary>
    public Task<FeishuDataResponse> EditEnumOptionAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/corehr/v1/common_data/meta_data/edit_enum_option",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrCompanyResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrCompanyResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Create /open-apis/corehr/v1/companies（Post /open-apis/corehr/v1/companies）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/corehr/v1/companies",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Delete /open-apis/corehr/v1/companies/:company_id（Delete /open-apis/corehr/v1/companies/:company_id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string companyid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/corehr/v1/companies/:company_id",
            PathParams =
            {
                ["company_id"] = companyid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Get /open-apis/corehr/v1/companies/:company_id（Get /open-apis/corehr/v1/companies/:company_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string companyid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/companies/:company_id",
            PathParams =
            {
                ["company_id"] = companyid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>List /open-apis/corehr/v1/companies（Get /open-apis/corehr/v1/companies）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/companies",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Patch /open-apis/corehr/v1/companies/:company_id（Patch /open-apis/corehr/v1/companies/:company_id）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string companyid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/corehr/v1/companies/:company_id",
            PathParams =
            {
                ["company_id"] = companyid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrCompensationStandardResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrCompensationStandardResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Match /open-apis/corehr/v1/compensation_standards/match（Get /open-apis/corehr/v1/compensation_standards/match）。</summary>
    public Task<FeishuDataResponse> MatchAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/compensation_standards/match",
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrContractResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrContractResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Create /open-apis/corehr/v1/contracts（Post /open-apis/corehr/v1/contracts）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/corehr/v1/contracts",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Delete /open-apis/corehr/v1/contracts/:contract_id（Delete /open-apis/corehr/v1/contracts/:contract_id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string contractid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/corehr/v1/contracts/:contract_id",
            PathParams =
            {
                ["contract_id"] = contractid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Get /open-apis/corehr/v1/contracts/:contract_id（Get /open-apis/corehr/v1/contracts/:contract_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string contractid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/contracts/:contract_id",
            PathParams =
            {
                ["contract_id"] = contractid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>List /open-apis/corehr/v1/contracts（Get /open-apis/corehr/v1/contracts）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/contracts",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Patch /open-apis/corehr/v1/contracts/:contract_id（Patch /open-apis/corehr/v1/contracts/:contract_id）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string contractid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/corehr/v1/contracts/:contract_id",
            PathParams =
            {
                ["contract_id"] = contractid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrCountryRegionResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrCountryRegionResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Get /open-apis/corehr/v1/country_regions/:country_region_id（Get /open-apis/corehr/v1/country_regions/:country_region_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string countryregionid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/country_regions/:country_region_id",
            PathParams =
            {
                ["country_region_id"] = countryregionid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>List /open-apis/corehr/v1/country_regions（Get /open-apis/corehr/v1/country_regions）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/country_regions",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrCurrencyResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrCurrencyResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Get /open-apis/corehr/v1/currencies/:currency_id（Get /open-apis/corehr/v1/currencies/:currency_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string currencyid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/currencies/:currency_id",
            PathParams =
            {
                ["currency_id"] = currencyid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>List /open-apis/corehr/v1/currencies（Get /open-apis/corehr/v1/currencies）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/currencies",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrCustomFieldResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrCustomFieldResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>GetByParam /open-apis/corehr/v1/custom_fields/get_by_param（Get /open-apis/corehr/v1/custom_fields/get_by_param）。</summary>
    public Task<FeishuDataResponse> GetByParamAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/custom_fields/get_by_param",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>ListObjectApiName /open-apis/corehr/v1/custom_fields/list_object_api_name（Get /open-apis/corehr/v1/custom_fields/list_object_api_name）。</summary>
    public Task<FeishuDataResponse> ListObjectApiNameAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/custom_fields/list_object_api_name",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Query /open-apis/corehr/v1/custom_fields/query（Get /open-apis/corehr/v1/custom_fields/query）。</summary>
    public Task<FeishuDataResponse> QueryAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/custom_fields/query",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrDepartmentResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrDepartmentResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Create /open-apis/corehr/v1/departments（Post /open-apis/corehr/v1/departments）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/corehr/v1/departments",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Delete /open-apis/corehr/v1/departments/:department_id（Delete /open-apis/corehr/v1/departments/:department_id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string departmentid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/corehr/v1/departments/:department_id",
            PathParams =
            {
                ["department_id"] = departmentid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Get /open-apis/corehr/v1/departments/:department_id（Get /open-apis/corehr/v1/departments/:department_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string departmentid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/departments/:department_id",
            PathParams =
            {
                ["department_id"] = departmentid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>List /open-apis/corehr/v1/departments（Get /open-apis/corehr/v1/departments）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/departments",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Patch /open-apis/corehr/v1/departments/:department_id（Patch /open-apis/corehr/v1/departments/:department_id）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string departmentid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/corehr/v1/departments/:department_id",
            PathParams =
            {
                ["department_id"] = departmentid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrEmployeeTypeResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrEmployeeTypeResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Create /open-apis/corehr/v1/employee_types（Post /open-apis/corehr/v1/employee_types）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/corehr/v1/employee_types",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Delete /open-apis/corehr/v1/employee_types/:employee_type_id（Delete /open-apis/corehr/v1/employee_types/:employee_type_id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string employeetypeid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/corehr/v1/employee_types/:employee_type_id",
            PathParams =
            {
                ["employee_type_id"] = employeetypeid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Get /open-apis/corehr/v1/employee_types/:employee_type_id（Get /open-apis/corehr/v1/employee_types/:employee_type_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string employeetypeid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/employee_types/:employee_type_id",
            PathParams =
            {
                ["employee_type_id"] = employeetypeid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>List /open-apis/corehr/v1/employee_types（Get /open-apis/corehr/v1/employee_types）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/employee_types",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Patch /open-apis/corehr/v1/employee_types/:employee_type_id（Patch /open-apis/corehr/v1/employee_types/:employee_type_id）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string employeetypeid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/corehr/v1/employee_types/:employee_type_id",
            PathParams =
            {
                ["employee_type_id"] = employeetypeid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrEmploymentResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrEmploymentResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Create /open-apis/corehr/v1/employments（Post /open-apis/corehr/v1/employments）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/corehr/v1/employments",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Delete /open-apis/corehr/v1/employments/:employment_id（Delete /open-apis/corehr/v1/employments/:employment_id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string employmentid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/corehr/v1/employments/:employment_id",
            PathParams =
            {
                ["employment_id"] = employmentid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Patch /open-apis/corehr/v1/employments/:employment_id（Patch /open-apis/corehr/v1/employments/:employment_id）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string employmentid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/corehr/v1/employments/:employment_id",
            PathParams =
            {
                ["employment_id"] = employmentid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrFileResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrFileResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Get /open-apis/corehr/v1/files/:id（Get /open-apis/corehr/v1/files/:id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string id, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/files/:id",
            PathParams =
            {
                ["id"] = id,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrJobResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrJobResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Create /open-apis/corehr/v1/jobs（Post /open-apis/corehr/v1/jobs）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/corehr/v1/jobs",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Delete /open-apis/corehr/v1/jobs/:job_id（Delete /open-apis/corehr/v1/jobs/:job_id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string jobid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/corehr/v1/jobs/:job_id",
            PathParams =
            {
                ["job_id"] = jobid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Get /open-apis/corehr/v1/jobs/:job_id（Get /open-apis/corehr/v1/jobs/:job_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string jobid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/jobs/:job_id",
            PathParams =
            {
                ["job_id"] = jobid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>List /open-apis/corehr/v1/jobs（Get /open-apis/corehr/v1/jobs）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/jobs",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Patch /open-apis/corehr/v1/jobs/:job_id（Patch /open-apis/corehr/v1/jobs/:job_id）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string jobid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/corehr/v1/jobs/:job_id",
            PathParams =
            {
                ["job_id"] = jobid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrJobChangeResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrJobChangeResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Create /open-apis/corehr/v1/job_changes（Post /open-apis/corehr/v1/job_changes）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/corehr/v1/job_changes",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrJobDataResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrJobDataResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Create /open-apis/corehr/v1/job_datas（Post /open-apis/corehr/v1/job_datas）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/corehr/v1/job_datas",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Delete /open-apis/corehr/v1/job_datas/:job_data_id（Delete /open-apis/corehr/v1/job_datas/:job_data_id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string jobdataid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/corehr/v1/job_datas/:job_data_id",
            PathParams =
            {
                ["job_data_id"] = jobdataid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Get /open-apis/corehr/v1/job_datas/:job_data_id（Get /open-apis/corehr/v1/job_datas/:job_data_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string jobdataid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/job_datas/:job_data_id",
            PathParams =
            {
                ["job_data_id"] = jobdataid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>List /open-apis/corehr/v1/job_datas（Get /open-apis/corehr/v1/job_datas）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/job_datas",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Patch /open-apis/corehr/v1/job_datas/:job_data_id（Patch /open-apis/corehr/v1/job_datas/:job_data_id）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string jobdataid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/corehr/v1/job_datas/:job_data_id",
            PathParams =
            {
                ["job_data_id"] = jobdataid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrJobFamilyResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrJobFamilyResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Create /open-apis/corehr/v1/job_families（Post /open-apis/corehr/v1/job_families）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/corehr/v1/job_families",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Delete /open-apis/corehr/v1/job_families/:job_family_id（Delete /open-apis/corehr/v1/job_families/:job_family_id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string jobfamilyid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/corehr/v1/job_families/:job_family_id",
            PathParams =
            {
                ["job_family_id"] = jobfamilyid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Get /open-apis/corehr/v1/job_families/:job_family_id（Get /open-apis/corehr/v1/job_families/:job_family_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string jobfamilyid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/job_families/:job_family_id",
            PathParams =
            {
                ["job_family_id"] = jobfamilyid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>List /open-apis/corehr/v1/job_families（Get /open-apis/corehr/v1/job_families）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/job_families",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Patch /open-apis/corehr/v1/job_families/:job_family_id（Patch /open-apis/corehr/v1/job_families/:job_family_id）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string jobfamilyid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/corehr/v1/job_families/:job_family_id",
            PathParams =
            {
                ["job_family_id"] = jobfamilyid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrJobLevelResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrJobLevelResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Create /open-apis/corehr/v1/job_levels（Post /open-apis/corehr/v1/job_levels）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/corehr/v1/job_levels",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Delete /open-apis/corehr/v1/job_levels/:job_level_id（Delete /open-apis/corehr/v1/job_levels/:job_level_id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string joblevelid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/corehr/v1/job_levels/:job_level_id",
            PathParams =
            {
                ["job_level_id"] = joblevelid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Get /open-apis/corehr/v1/job_levels/:job_level_id（Get /open-apis/corehr/v1/job_levels/:job_level_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string joblevelid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/job_levels/:job_level_id",
            PathParams =
            {
                ["job_level_id"] = joblevelid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>List /open-apis/corehr/v1/job_levels（Get /open-apis/corehr/v1/job_levels）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/job_levels",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Patch /open-apis/corehr/v1/job_levels/:job_level_id（Patch /open-apis/corehr/v1/job_levels/:job_level_id）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string joblevelid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/corehr/v1/job_levels/:job_level_id",
            PathParams =
            {
                ["job_level_id"] = joblevelid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrLeaveResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrLeaveResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>CalendarByScope /open-apis/corehr/v1/leaves/calendar_by_scope（Get /open-apis/corehr/v1/leaves/calendar_by_scope）。</summary>
    public Task<FeishuDataResponse> CalendarByScopeAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/leaves/calendar_by_scope",
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>LeaveBalances /open-apis/corehr/v1/leaves/leave_balances（Get /open-apis/corehr/v1/leaves/leave_balances）。</summary>
    public Task<FeishuDataResponse> LeaveBalancesAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/leaves/leave_balances",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>LeaveRequestHistory /open-apis/corehr/v1/leaves/leave_request_history（Get /open-apis/corehr/v1/leaves/leave_request_history）。</summary>
    public Task<FeishuDataResponse> LeaveRequestHistoryAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/leaves/leave_request_history",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>LeaveTypes /open-apis/corehr/v1/leaves/leave_types（Get /open-apis/corehr/v1/leaves/leave_types）。</summary>
    public Task<FeishuDataResponse> LeaveTypesAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/leaves/leave_types",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>WorkCalendar /open-apis/corehr/v1/leaves/work_calendar（Post /open-apis/corehr/v1/leaves/work_calendar）。</summary>
    public Task<FeishuDataResponse> WorkCalendarAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/corehr/v1/leaves/work_calendar",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>WorkCalendarDate /open-apis/corehr/v1/leaves/work_calendar_date（Post /open-apis/corehr/v1/leaves/work_calendar_date）。</summary>
    public Task<FeishuDataResponse> WorkCalendarDateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/corehr/v1/leaves/work_calendar_date",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrLeaveGrantingRecordResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrLeaveGrantingRecordResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Create /open-apis/corehr/v1/leave_granting_records（Post /open-apis/corehr/v1/leave_granting_records）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/corehr/v1/leave_granting_records",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Delete /open-apis/corehr/v1/leave_granting_records/:leave_granting_record_id（Delete /open-apis/corehr/v1/leave_granting_records/:leave_granting_record_id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string leavegrantingrecordid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/corehr/v1/leave_granting_records/:leave_granting_record_id",
            PathParams =
            {
                ["leave_granting_record_id"] = leavegrantingrecordid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrLocationResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrLocationResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Create /open-apis/corehr/v1/locations（Post /open-apis/corehr/v1/locations）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/corehr/v1/locations",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Delete /open-apis/corehr/v1/locations/:location_id（Delete /open-apis/corehr/v1/locations/:location_id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string locationid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/corehr/v1/locations/:location_id",
            PathParams =
            {
                ["location_id"] = locationid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Get /open-apis/corehr/v1/locations/:location_id（Get /open-apis/corehr/v1/locations/:location_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string locationid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/locations/:location_id",
            PathParams =
            {
                ["location_id"] = locationid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>List /open-apis/corehr/v1/locations（Get /open-apis/corehr/v1/locations）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/locations",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrNationalIdTypeResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrNationalIdTypeResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Create /open-apis/corehr/v1/national_id_types（Post /open-apis/corehr/v1/national_id_types）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/corehr/v1/national_id_types",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Delete /open-apis/corehr/v1/national_id_types/:national_id_type_id（Delete /open-apis/corehr/v1/national_id_types/:national_id_type_id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string nationalidtypeid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/corehr/v1/national_id_types/:national_id_type_id",
            PathParams =
            {
                ["national_id_type_id"] = nationalidtypeid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Get /open-apis/corehr/v1/national_id_types/:national_id_type_id（Get /open-apis/corehr/v1/national_id_types/:national_id_type_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string nationalidtypeid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/national_id_types/:national_id_type_id",
            PathParams =
            {
                ["national_id_type_id"] = nationalidtypeid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>List /open-apis/corehr/v1/national_id_types（Get /open-apis/corehr/v1/national_id_types）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/national_id_types",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Patch /open-apis/corehr/v1/national_id_types/:national_id_type_id（Patch /open-apis/corehr/v1/national_id_types/:national_id_type_id）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string nationalidtypeid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/corehr/v1/national_id_types/:national_id_type_id",
            PathParams =
            {
                ["national_id_type_id"] = nationalidtypeid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrOffboardingResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrOffboardingResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Query /open-apis/corehr/v1/offboardings/query（Post /open-apis/corehr/v1/offboardings/query）。</summary>
    public Task<FeishuDataResponse> QueryAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/corehr/v1/offboardings/query",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Search /open-apis/corehr/v1/offboardings/search（Post /open-apis/corehr/v1/offboardings/search）。</summary>
    public Task<FeishuDataResponse> SearchAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/corehr/v1/offboardings/search",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Submit /open-apis/corehr/v1/offboardings/submit（Post /open-apis/corehr/v1/offboardings/submit）。</summary>
    public Task<FeishuDataResponse> SubmitAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/corehr/v1/offboardings/submit",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrPersonResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrPersonResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Create /open-apis/corehr/v1/persons（Post /open-apis/corehr/v1/persons）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/corehr/v1/persons",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Delete /open-apis/corehr/v1/persons/:person_id（Delete /open-apis/corehr/v1/persons/:person_id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string personid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/corehr/v1/persons/:person_id",
            PathParams =
            {
                ["person_id"] = personid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Get /open-apis/corehr/v1/persons/:person_id（Get /open-apis/corehr/v1/persons/:person_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string personid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/persons/:person_id",
            PathParams =
            {
                ["person_id"] = personid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Patch /open-apis/corehr/v1/persons/:person_id（Patch /open-apis/corehr/v1/persons/:person_id）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string personid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/corehr/v1/persons/:person_id",
            PathParams =
            {
                ["person_id"] = personid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Upload /open-apis/corehr/v1/persons/upload（Post /open-apis/corehr/v1/persons/upload）。</summary>
    public Task<FeishuDataResponse> UploadAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/corehr/v1/persons/upload",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrPreHireResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrPreHireResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Delete /open-apis/corehr/v1/pre_hires/:pre_hire_id（Delete /open-apis/corehr/v1/pre_hires/:pre_hire_id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string prehireid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/corehr/v1/pre_hires/:pre_hire_id",
            PathParams =
            {
                ["pre_hire_id"] = prehireid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Get /open-apis/corehr/v1/pre_hires/:pre_hire_id（Get /open-apis/corehr/v1/pre_hires/:pre_hire_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string prehireid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/pre_hires/:pre_hire_id",
            PathParams =
            {
                ["pre_hire_id"] = prehireid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>List /open-apis/corehr/v1/pre_hires（Get /open-apis/corehr/v1/pre_hires）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/pre_hires",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Patch /open-apis/corehr/v1/pre_hires/:pre_hire_id（Patch /open-apis/corehr/v1/pre_hires/:pre_hire_id）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string prehireid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/corehr/v1/pre_hires/:pre_hire_id",
            PathParams =
            {
                ["pre_hire_id"] = prehireid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrProcessFormVariableDataResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrProcessFormVariableDataResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Get /open-apis/corehr/v1/processes/:process_id/form_variable_data（Get /open-apis/corehr/v1/processes/:process_id/form_variable_data）。</summary>
    public Task<FeishuDataResponse> GetAsync(string processid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/processes/:process_id/form_variable_data",
            PathParams =
            {
                ["process_id"] = processid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrSecurityGroupResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrSecurityGroupResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>List /open-apis/corehr/v1/security_groups（Get /open-apis/corehr/v1/security_groups）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/security_groups",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Query /open-apis/corehr/v1/security_groups/query（Post /open-apis/corehr/v1/security_groups/query）。</summary>
    public Task<FeishuDataResponse> QueryAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/corehr/v1/security_groups/query",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrSubdivisionResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrSubdivisionResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Get /open-apis/corehr/v1/subdivisions/:subdivision_id（Get /open-apis/corehr/v1/subdivisions/:subdivision_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string subdivisionid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/subdivisions/:subdivision_id",
            PathParams =
            {
                ["subdivision_id"] = subdivisionid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>List /open-apis/corehr/v1/subdivisions（Get /open-apis/corehr/v1/subdivisions）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/subdivisions",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrSubregionResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrSubregionResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Get /open-apis/corehr/v1/subregions/:subregion_id（Get /open-apis/corehr/v1/subregions/:subregion_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string subregionid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/subregions/:subregion_id",
            PathParams =
            {
                ["subregion_id"] = subregionid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>List /open-apis/corehr/v1/subregions（Get /open-apis/corehr/v1/subregions）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/subregions",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrTransferReasonResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrTransferReasonResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Query /open-apis/corehr/v1/transfer_reasons/query（Get /open-apis/corehr/v1/transfer_reasons/query）。</summary>
    public Task<FeishuDataResponse> QueryAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/transfer_reasons/query",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrTransferTypeResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrTransferTypeResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Query /open-apis/corehr/v1/transfer_types/query（Get /open-apis/corehr/v1/transfer_types/query）。</summary>
    public Task<FeishuDataResponse> QueryAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/transfer_types/query",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CorehrWorkingHoursTypeResource
{
    private readonly RequestPipeline _pipeline;

    internal CorehrWorkingHoursTypeResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Create /open-apis/corehr/v1/working_hours_types（Post /open-apis/corehr/v1/working_hours_types）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/corehr/v1/working_hours_types",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Delete /open-apis/corehr/v1/working_hours_types/:working_hours_type_id（Delete /open-apis/corehr/v1/working_hours_types/:working_hours_type_id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string workinghourstypeid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/corehr/v1/working_hours_types/:working_hours_type_id",
            PathParams =
            {
                ["working_hours_type_id"] = workinghourstypeid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Get /open-apis/corehr/v1/working_hours_types/:working_hours_type_id（Get /open-apis/corehr/v1/working_hours_types/:working_hours_type_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string workinghourstypeid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/working_hours_types/:working_hours_type_id",
            PathParams =
            {
                ["working_hours_type_id"] = workinghourstypeid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>List /open-apis/corehr/v1/working_hours_types（Get /open-apis/corehr/v1/working_hours_types）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/corehr/v1/working_hours_types",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>Patch /open-apis/corehr/v1/working_hours_types/:working_hours_type_id（Patch /open-apis/corehr/v1/working_hours_types/:working_hours_type_id）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string workinghourstypeid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/corehr/v1/working_hours_types/:working_hours_type_id",
            PathParams =
            {
                ["working_hours_type_id"] = workinghourstypeid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

}
