// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.Block;

/// <summary>小黑板 Block（block/v2）（生成代码：3 个端点）。</summary>
public sealed class BlockService
{
    private readonly RequestPipeline _pipeline;

    internal BlockService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        Entity = new BlockEntityResource(pipeline);
        Message = new BlockMessageResource(pipeline);
    }

    /// <summary>Entity 资源。</summary>
    public BlockEntityResource Entity { get; }
    /// <summary>Message 资源。</summary>
    public BlockMessageResource Message { get; }

public sealed class BlockEntityResource
{
    private readonly RequestPipeline _pipeline;

    internal BlockEntityResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>创建 BlockEntity（POST /open-apis/block/v2/entities）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/block/v2/entities",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>更新 BlockEntity（PUT /open-apis/block/v2/entities/:block_id）。</summary>
    public Task<FeishuDataResponse> UpdateAsync(string blockid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Put,
            Path = "/open-apis/block/v2/entities/:block_id",
            PathParams =
            {
                ["block_id"] = blockid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class BlockMessageResource
{
    private readonly RequestPipeline _pipeline;

    internal BlockMessageResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>Block 协同数据推送（POST /open-apis/block/v2/message）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/block/v2/message",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

}
