// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.Aily;

/// <summary>智能伙伴（aily/v1）（生成代码：31 个端点）。</summary>
public sealed class AilyService
{
    private readonly RequestPipeline _pipeline;

    internal AilyService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        AgentArtifact = new AilyAgentArtifactResource(pipeline);
        AgentAttachment = new AilyAgentAttachmentResource(pipeline);
        AgentChat = new AilyAgentChatResource(pipeline);
        AgentChatSession = new AilyAgentChatSessionResource(pipeline);
        AgentVisibility = new AilyAgentVisibilityResource(pipeline);
        AilySession = new AilyAilySessionResource(pipeline);
        AilyMessage = new AilyAilyMessageResource(pipeline);
        AilySessionRun = new AilyAilySessionRunResource(pipeline);
        AppDataAsset = new AilyAppDataAssetResource(pipeline);
        AppDataAssetTag = new AilyAppDataAssetTagResource(pipeline);
        AppKnowledge = new AilyAppKnowledgeResource(pipeline);
        AppSkill = new AilyAppSkillResource(pipeline);
        TenantAppStat = new AilyTenantAppStatResource(pipeline);
    }

    /// <summary>AgentArtifact 资源。</summary>
    public AilyAgentArtifactResource AgentArtifact { get; }
    /// <summary>AgentAttachment 资源。</summary>
    public AilyAgentAttachmentResource AgentAttachment { get; }
    /// <summary>AgentChat 资源。</summary>
    public AilyAgentChatResource AgentChat { get; }
    /// <summary>AgentChatSession 资源。</summary>
    public AilyAgentChatSessionResource AgentChatSession { get; }
    /// <summary>AgentVisibility 资源。</summary>
    public AilyAgentVisibilityResource AgentVisibility { get; }
    /// <summary>AilySession 资源。</summary>
    public AilyAilySessionResource AilySession { get; }
    /// <summary>AilyMessage 资源。</summary>
    public AilyAilyMessageResource AilyMessage { get; }
    /// <summary>AilySessionRun 资源。</summary>
    public AilyAilySessionRunResource AilySessionRun { get; }
    /// <summary>AppDataAsset 资源。</summary>
    public AilyAppDataAssetResource AppDataAsset { get; }
    /// <summary>AppDataAssetTag 资源。</summary>
    public AilyAppDataAssetTagResource AppDataAssetTag { get; }
    /// <summary>AppKnowledge 资源。</summary>
    public AilyAppKnowledgeResource AppKnowledge { get; }
    /// <summary>AppSkill 资源。</summary>
    public AilyAppSkillResource AppSkill { get; }
    /// <summary>TenantAppStat 资源。</summary>
    public AilyTenantAppStatResource TenantAppStat { get; }

public sealed class AilyAgentArtifactResource
{
    private readonly RequestPipeline _pipeline;

    internal AilyAgentArtifactResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>下载智能体产物（GET /open-apis/aily/v1/agents/:agent_id/artifacts/:agent_artifact_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string agentid, string agentartifactid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/aily/v1/agents/:agent_id/artifacts/:agent_artifact_id",
            PathParams =
            {
                ["agent_id"] = agentid,
                ["agent_artifact_id"] = agentartifactid,
            },
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class AilyAgentAttachmentResource
{
    private readonly RequestPipeline _pipeline;

    internal AilyAgentAttachmentResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>上传附件（POST /open-apis/aily/v1/agents/:agent_id/attachments）。</summary>
    public Task<FeishuDataResponse> CreateAsync(string agentid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/aily/v1/agents/:agent_id/attachments",
            PathParams =
            {
                ["agent_id"] = agentid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class AilyAgentChatResource
{
    private readonly RequestPipeline _pipeline;

    internal AilyAgentChatResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>发起智能体对话（POST /open-apis/aily/v1/agents/:agent_id/chats）。</summary>
    public Task<FeishuDataResponse> CreateAsync(string agentid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/aily/v1/agents/:agent_id/chats",
            PathParams =
            {
                ["agent_id"] = agentid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取对话结果（GET /open-apis/aily/v1/agents/:agent_id/chats/:agent_chat_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string agentid, string agentchatid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/aily/v1/agents/:agent_id/chats/:agent_chat_id",
            PathParams =
            {
                ["agent_id"] = agentid,
                ["agent_chat_id"] = agentchatid,
            },
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class AilyAgentChatSessionResource
{
    private readonly RequestPipeline _pipeline;

    internal AilyAgentChatSessionResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>创建会话（POST /open-apis/aily/v1/agents/:agent_id/sessions）。</summary>
    public Task<FeishuDataResponse> CreateAsync(string agentid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/aily/v1/agents/:agent_id/sessions",
            PathParams =
            {
                ["agent_id"] = agentid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>查询会话列表（GET /open-apis/aily/v1/agents/:agent_id/sessions）。</summary>
    public Task<FeishuDataResponse> ListAsync(string agentid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/aily/v1/agents/:agent_id/sessions",
            PathParams =
            {
                ["agent_id"] = agentid,
            },
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取指定会话信息（GET /open-apis/aily/v1/agents/:agent_id/sessions/:agent_chat_session_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string agentid, string agentchatsessionid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/aily/v1/agents/:agent_id/sessions/:agent_chat_session_id",
            PathParams =
            {
                ["agent_id"] = agentid,
                ["agent_chat_session_id"] = agentchatsessionid,
            },
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>删除会话（DELETE /open-apis/aily/v1/agents/:agent_id/sessions/:agent_chat_session_id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string agentid, string agentchatsessionid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/aily/v1/agents/:agent_id/sessions/:agent_chat_session_id",
            PathParams =
            {
                ["agent_id"] = agentid,
                ["agent_chat_session_id"] = agentchatsessionid,
            },
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class AilyAgentVisibilityResource
{
    private readonly RequestPipeline _pipeline;

    internal AilyAgentVisibilityResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>获取智能体可见性（POST /open-apis/aily/v1/agents/:agent_id/agent_visibility/check）。</summary>
    public Task<FeishuDataResponse> CheckAsync(string agentid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/aily/v1/agents/:agent_id/agent_visibility/check",
            PathParams =
            {
                ["agent_id"] = agentid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class AilyAilySessionResource
{
    private readonly RequestPipeline _pipeline;

    internal AilyAilySessionResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>创建会话（POST /open-apis/aily/v1/sessions）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/aily/v1/sessions",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取会话（GET /open-apis/aily/v1/sessions/:aily_session_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string ailysessionid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/aily/v1/sessions/:aily_session_id",
            PathParams =
            {
                ["aily_session_id"] = ailysessionid,
            },
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>更新会话（PUT /open-apis/aily/v1/sessions/:aily_session_id）。</summary>
    public Task<FeishuDataResponse> UpdateAsync(string ailysessionid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Put,
            Path = "/open-apis/aily/v1/sessions/:aily_session_id",
            PathParams =
            {
                ["aily_session_id"] = ailysessionid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>删除会话（DELETE /open-apis/aily/v1/sessions/:aily_session_id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string ailysessionid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/aily/v1/sessions/:aily_session_id",
            PathParams =
            {
                ["aily_session_id"] = ailysessionid,
            },
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class AilyAilyMessageResource
{
    private readonly RequestPipeline _pipeline;

    internal AilyAilyMessageResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>发送 Aily 消息（POST /open-apis/aily/v1/sessions/:aily_session_id/messages）。</summary>
    public Task<FeishuDataResponse> CreateAsync(string ailysessionid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/aily/v1/sessions/:aily_session_id/messages",
            PathParams =
            {
                ["aily_session_id"] = ailysessionid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取 Aily 消息（GET /open-apis/aily/v1/sessions/:aily_session_id/messages/:aily_message_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string ailysessionid, string ailymessageid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/aily/v1/sessions/:aily_session_id/messages/:aily_message_id",
            PathParams =
            {
                ["aily_session_id"] = ailysessionid,
                ["aily_message_id"] = ailymessageid,
            },
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>列出 Aily 消息（GET /open-apis/aily/v1/sessions/:aily_session_id/messages）。</summary>
    public Task<FeishuDataResponse> ListAsync(string ailysessionid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/aily/v1/sessions/:aily_session_id/messages",
            PathParams =
            {
                ["aily_session_id"] = ailysessionid,
            },
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class AilyAilySessionRunResource
{
    private readonly RequestPipeline _pipeline;

    internal AilyAilySessionRunResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>创建运行（POST /open-apis/aily/v1/sessions/:aily_session_id/runs）。</summary>
    public Task<FeishuDataResponse> CreateAsync(string ailysessionid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/aily/v1/sessions/:aily_session_id/runs",
            PathParams =
            {
                ["aily_session_id"] = ailysessionid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取运行（GET /open-apis/aily/v1/sessions/:aily_session_id/runs/:run_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string ailysessionid, string runid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/aily/v1/sessions/:aily_session_id/runs/:run_id",
            PathParams =
            {
                ["aily_session_id"] = ailysessionid,
                ["run_id"] = runid,
            },
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>列出运行（GET /open-apis/aily/v1/sessions/:aily_session_id/runs）。</summary>
    public Task<FeishuDataResponse> ListAsync(string ailysessionid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/aily/v1/sessions/:aily_session_id/runs",
            PathParams =
            {
                ["aily_session_id"] = ailysessionid,
            },
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>中止一次运行（POST /open-apis/aily/v1/sessions/:aily_session_id/runs/:run_id/cancel）。</summary>
    public Task<FeishuDataResponse> CancelAsync(string ailysessionid, string runid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/aily/v1/sessions/:aily_session_id/runs/:run_id/cancel",
            PathParams =
            {
                ["aily_session_id"] = ailysessionid,
                ["run_id"] = runid,
            },
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class AilyAppDataAssetResource
{
    private readonly RequestPipeline _pipeline;

    internal AilyAppDataAssetResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>创建数据知识（POST /open-apis/aily/v1/apps/:app_id/data_assets）。</summary>
    public Task<FeishuDataResponse> CreateAsync(string appid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/aily/v1/apps/:app_id/data_assets",
            PathParams =
            {
                ["app_id"] = appid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取数据知识列表（GET /open-apis/aily/v1/apps/:app_id/data_assets）。</summary>
    public Task<FeishuDataResponse> ListAsync(string appid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/aily/v1/apps/:app_id/data_assets",
            PathParams =
            {
                ["app_id"] = appid,
            },
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取数据知识（GET /open-apis/aily/v1/apps/:app_id/data_assets/:data_asset_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string appid, string dataassetid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/aily/v1/apps/:app_id/data_assets/:data_asset_id",
            PathParams =
            {
                ["app_id"] = appid,
                ["data_asset_id"] = dataassetid,
            },
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>删除数据知识（DELETE /open-apis/aily/v1/apps/:app_id/data_assets/:data_asset_id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string appid, string dataassetid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/aily/v1/apps/:app_id/data_assets/:data_asset_id",
            PathParams =
            {
                ["app_id"] = appid,
                ["data_asset_id"] = dataassetid,
            },
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>上传数据知识文件（POST /open-apis/aily/v1/apps/:app_id/data_assets/upload_file）。</summary>
    public Task<FeishuDataResponse> UploadFileAsync(string appid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/aily/v1/apps/:app_id/data_assets/upload_file",
            PathParams =
            {
                ["app_id"] = appid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class AilyAppDataAssetTagResource
{
    private readonly RequestPipeline _pipeline;

    internal AilyAppDataAssetTagResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>获取数据知识分类列表（GET /open-apis/aily/v1/apps/:app_id/data_asset_tags）。</summary>
    public Task<FeishuDataResponse> ListAsync(string appid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/aily/v1/apps/:app_id/data_asset_tags",
            PathParams =
            {
                ["app_id"] = appid,
            },
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class AilyAppKnowledgeResource
{
    private readonly RequestPipeline _pipeline;

    internal AilyAppKnowledgeResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>执行数据知识问答（POST /open-apis/aily/v1/apps/:app_id/knowledges/ask）。</summary>
    public Task<FeishuDataResponse> AskAsync(string appid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/aily/v1/apps/:app_id/knowledges/ask",
            PathParams =
            {
                ["app_id"] = appid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class AilyAppSkillResource
{
    private readonly RequestPipeline _pipeline;

    internal AilyAppSkillResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>查询技能列表（GET /open-apis/aily/v1/apps/:app_id/skills）。</summary>
    public Task<FeishuDataResponse> ListAsync(string appid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/aily/v1/apps/:app_id/skills",
            PathParams =
            {
                ["app_id"] = appid,
            },
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取技能信息（GET /open-apis/aily/v1/apps/:app_id/skills/:skill_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string appid, string skillid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/aily/v1/apps/:app_id/skills/:skill_id",
            PathParams =
            {
                ["app_id"] = appid,
                ["skill_id"] = skillid,
            },
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>调用技能（POST /open-apis/aily/v1/apps/:app_id/skills/:skill_id/start）。</summary>
    public Task<FeishuDataResponse> StartAsync(string appid, string skillid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/aily/v1/apps/:app_id/skills/:skill_id/start",
            PathParams =
            {
                ["app_id"] = appid,
                ["skill_id"] = skillid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class AilyTenantAppStatResource
{
    private readonly RequestPipeline _pipeline;

    internal AilyTenantAppStatResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>查询应用统计数据（GET /open-apis/aily/v1/app_stats）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/aily/v1/app_stats",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

}
