// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.SpeechToText;

/// <summary>语音转文字（speech_to_text/v1 ASR）（生成代码：2 个端点）。</summary>
public sealed class SpeechToTextService
{
    private readonly RequestPipeline _pipeline;

    internal SpeechToTextService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        Speech = new SpeechToTextSpeechResource(pipeline);
    }

    /// <summary>Speech 资源。</summary>
    public SpeechToTextSpeechResource Speech { get; }

public sealed class SpeechToTextSpeechResource
{
    private readonly RequestPipeline _pipeline;

    internal SpeechToTextSpeechResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>识别语音文件（≤60s）（POST /open-apis/speech_to_text/v1/speech/file_recognize）。</summary>
    public Task<FeishuDataResponse> FileRecognizeAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/speech_to_text/v1/speech/file_recognize",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>流式语音识别（POST /open-apis/speech_to_text/v1/speech/stream_recognize）。</summary>
    public Task<FeishuDataResponse> StreamRecognizeAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/speech_to_text/v1/speech/stream_recognize",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

}
