// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.Bitable;

/// <summary>多维表格（bitable/v1 高频端点）（生成代码：13 个端点）。</summary>
public sealed class BitableService
{
    private readonly RequestPipeline _pipeline;

    internal BitableService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        App = new BitableAppResource(pipeline);
        Table = new BitableTableResource(pipeline);
        Record = new BitableRecordResource(pipeline);
    }

    /// <summary>App 资源。</summary>
    public BitableAppResource App { get; }
    /// <summary>Table 资源。</summary>
    public BitableTableResource Table { get; }
    /// <summary>Record 资源。</summary>
    public BitableRecordResource Record { get; }

public sealed class BitableAppResource
{
    private readonly RequestPipeline _pipeline;

    internal BitableAppResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>创建多维表格（POST /open-apis/bitable/v1/apps）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/bitable/v1/apps",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取多维表格元数据（GET /open-apis/bitable/v1/apps/:app_token）。</summary>
    public Task<FeishuDataResponse> GetAsync(string apptoken, IDictionary<string, string>? query = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/bitable/v1/apps/:app_token",
            PathParams =
            {
                ["app_token"] = apptoken,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>更新多维表格（PUT /open-apis/bitable/v1/apps/:app_token）。</summary>
    public Task<FeishuDataResponse> UpdateAsync(string apptoken, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Put,
            Path = "/open-apis/bitable/v1/apps/:app_token",
            PathParams =
            {
                ["app_token"] = apptoken,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class BitableTableResource
{
    private readonly RequestPipeline _pipeline;

    internal BitableTableResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>新增数据表（POST /open-apis/bitable/v1/apps/:app_token/tables）。</summary>
    public Task<FeishuDataResponse> CreateAsync(string apptoken, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/bitable/v1/apps/:app_token/tables",
            PathParams =
            {
                ["app_token"] = apptoken,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>批量获取数据表（GET /open-apis/bitable/v1/apps/:app_token/tables）。</summary>
    public Task<FeishuDataResponse> ListAsync(string apptoken, IDictionary<string, string>? query = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/bitable/v1/apps/:app_token/tables",
            PathParams =
            {
                ["app_token"] = apptoken,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>批量获取数据表：自动翻页枚举 data.items。</summary>
    public async IAsyncEnumerable<System.Text.Json.JsonElement> ListAsyncEnumerate(string apptoken, IDictionary<string, string>? query = null, RequestOptions? options = null, int? limit = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var emitted = 0;
        string? pageToken = null;
        do
        {
            var pageQuery = query == null ? new Dictionary<string, string>() : new Dictionary<string, string>(query);
            if (pageToken != null) pageQuery["page_token"] = pageToken;
            var page = await ListAsync(apptoken, pageQuery, options, cancellationToken);
            page.EnsureSuccess();
            if (page.Data is not { ValueKind: System.Text.Json.JsonValueKind.Object } data) yield break;
            if (!data.TryGetProperty("items", out var items) || items.ValueKind != System.Text.Json.JsonValueKind.Array) yield break;
            foreach (var item in items.EnumerateArray())
            {
                if (limit.HasValue && emitted >= limit.Value) yield break;
                emitted++;
                yield return item;
            }
            pageToken = page.PageToken is { Length: > 0 } ? page.PageToken : null;
        } while (pageToken != null);
    }

    /// <summary>查询单个数据表（GET /open-apis/bitable/v1/apps/:app_token/tables/:table_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string apptoken, string tableid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/bitable/v1/apps/:app_token/tables/:table_id",
            PathParams =
            {
                ["app_token"] = apptoken,
                ["table_id"] = tableid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class BitableRecordResource
{
    private readonly RequestPipeline _pipeline;

    internal BitableRecordResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>新增记录（POST /open-apis/bitable/v1/apps/:app_token/tables/:table_id/records）。</summary>
    public Task<FeishuDataResponse> CreateAsync(string apptoken, string tableid, IDictionary<string, string>? query = null, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/bitable/v1/apps/:app_token/tables/:table_id/records",
            PathParams =
            {
                ["app_token"] = apptoken,
                ["table_id"] = tableid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>批量新增记录（POST /open-apis/bitable/v1/apps/:app_token/tables/:table_id/records/batch_create）。</summary>
    public Task<FeishuDataResponse> BatchCreateAsync(string apptoken, string tableid, IDictionary<string, string>? query = null, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/bitable/v1/apps/:app_token/tables/:table_id/records/batch_create",
            PathParams =
            {
                ["app_token"] = apptoken,
                ["table_id"] = tableid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>查询记录（GET /open-apis/bitable/v1/apps/:app_token/tables/:table_id/records/:record_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string apptoken, string tableid, string recordid, IDictionary<string, string>? query = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/bitable/v1/apps/:app_token/tables/:table_id/records/:record_id",
            PathParams =
            {
                ["app_token"] = apptoken,
                ["table_id"] = tableid,
                ["record_id"] = recordid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>更新记录（PUT /open-apis/bitable/v1/apps/:app_token/tables/:table_id/records/:record_id）。</summary>
    public Task<FeishuDataResponse> UpdateAsync(string apptoken, string tableid, string recordid, IDictionary<string, string>? query = null, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Put,
            Path = "/open-apis/bitable/v1/apps/:app_token/tables/:table_id/records/:record_id",
            PathParams =
            {
                ["app_token"] = apptoken,
                ["table_id"] = tableid,
                ["record_id"] = recordid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>删除记录（DELETE /open-apis/bitable/v1/apps/:app_token/tables/:table_id/records/:record_id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string apptoken, string tableid, string recordid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/bitable/v1/apps/:app_token/tables/:table_id/records/:record_id",
            PathParams =
            {
                ["app_token"] = apptoken,
                ["table_id"] = tableid,
                ["record_id"] = recordid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>查询记录（分页）（GET /open-apis/bitable/v1/apps/:app_token/tables/:table_id/records）。</summary>
    public Task<FeishuDataResponse> ListAsync(string apptoken, string tableid, IDictionary<string, string>? query = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/bitable/v1/apps/:app_token/tables/:table_id/records",
            PathParams =
            {
                ["app_token"] = apptoken,
                ["table_id"] = tableid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>查询记录（分页）：自动翻页枚举 data.items。</summary>
    public async IAsyncEnumerable<System.Text.Json.JsonElement> ListAsyncEnumerate(string apptoken, string tableid, IDictionary<string, string>? query = null, RequestOptions? options = null, int? limit = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var emitted = 0;
        string? pageToken = null;
        do
        {
            var pageQuery = query == null ? new Dictionary<string, string>() : new Dictionary<string, string>(query);
            if (pageToken != null) pageQuery["page_token"] = pageToken;
            var page = await ListAsync(apptoken, tableid, pageQuery, options, cancellationToken);
            page.EnsureSuccess();
            if (page.Data is not { ValueKind: System.Text.Json.JsonValueKind.Object } data) yield break;
            if (!data.TryGetProperty("items", out var items) || items.ValueKind != System.Text.Json.JsonValueKind.Array) yield break;
            foreach (var item in items.EnumerateArray())
            {
                if (limit.HasValue && emitted >= limit.Value) yield break;
                emitted++;
                yield return item;
            }
            pageToken = page.PageToken is { Length: > 0 } ? page.PageToken : null;
        } while (pageToken != null);
    }

    /// <summary>检索记录（分页）（POST /open-apis/bitable/v1/apps/:app_token/tables/:table_id/records/search）。</summary>
    public Task<FeishuDataResponse> SearchAsync(string apptoken, string tableid, IDictionary<string, string>? query = null, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/bitable/v1/apps/:app_token/tables/:table_id/records/search",
            PathParams =
            {
                ["app_token"] = apptoken,
                ["table_id"] = tableid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>检索记录（分页）：自动翻页枚举 data.items。</summary>
    public async IAsyncEnumerable<System.Text.Json.JsonElement> SearchAsyncEnumerate(string apptoken, string tableid, IDictionary<string, string>? query = null, RequestOptions? options = null, int? limit = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var emitted = 0;
        string? pageToken = null;
        do
        {
            var pageQuery = query == null ? new Dictionary<string, string>() : new Dictionary<string, string>(query);
            if (pageToken != null) pageQuery["page_token"] = pageToken;
            var page = await SearchAsync(apptoken, tableid, pageQuery, null, options, cancellationToken);
            page.EnsureSuccess();
            if (page.Data is not { ValueKind: System.Text.Json.JsonValueKind.Object } data) yield break;
            if (!data.TryGetProperty("items", out var items) || items.ValueKind != System.Text.Json.JsonValueKind.Array) yield break;
            foreach (var item in items.EnumerateArray())
            {
                if (limit.HasValue && emitted >= limit.Value) yield break;
                emitted++;
                yield return item;
            }
            pageToken = page.PageToken is { Length: > 0 } ? page.PageToken : null;
        } while (pageToken != null);
    }

}

}
