// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.Compensation;

/// <summary>薪酬（compensation/v1）（生成代码：21 个端点）。</summary>
public sealed class CompensationService
{
    private readonly RequestPipeline _pipeline;

    internal CompensationService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        Archive = new CompensationArchiveResource(pipeline);
        ChangeReason = new CompensationChangeReasonResource(pipeline);
        Indicator = new CompensationIndicatorResource(pipeline);
        Item = new CompensationItemResource(pipeline);
        ItemCategory = new CompensationItemCategoryResource(pipeline);
        LumpSumPayment = new CompensationLumpSumPaymentResource(pipeline);
        Plan = new CompensationPlanResource(pipeline);
        RecurringPayment = new CompensationRecurringPaymentResource(pipeline);
        SocialArchive = new CompensationSocialArchiveResource(pipeline);
        SocialArchiveAdjustRecord = new CompensationSocialArchiveAdjustRecordResource(pipeline);
        SocialInsurance = new CompensationSocialInsuranceResource(pipeline);
        SocialPlan = new CompensationSocialPlanResource(pipeline);
    }

    /// <summary>Archive 资源。</summary>
    public CompensationArchiveResource Archive { get; }
    /// <summary>ChangeReason 资源。</summary>
    public CompensationChangeReasonResource ChangeReason { get; }
    /// <summary>Indicator 资源。</summary>
    public CompensationIndicatorResource Indicator { get; }
    /// <summary>Item 资源。</summary>
    public CompensationItemResource Item { get; }
    /// <summary>ItemCategory 资源。</summary>
    public CompensationItemCategoryResource ItemCategory { get; }
    /// <summary>LumpSumPayment 资源。</summary>
    public CompensationLumpSumPaymentResource LumpSumPayment { get; }
    /// <summary>Plan 资源。</summary>
    public CompensationPlanResource Plan { get; }
    /// <summary>RecurringPayment 资源。</summary>
    public CompensationRecurringPaymentResource RecurringPayment { get; }
    /// <summary>SocialArchive 资源。</summary>
    public CompensationSocialArchiveResource SocialArchive { get; }
    /// <summary>SocialArchiveAdjustRecord 资源。</summary>
    public CompensationSocialArchiveAdjustRecordResource SocialArchiveAdjustRecord { get; }
    /// <summary>SocialInsurance 资源。</summary>
    public CompensationSocialInsuranceResource SocialInsurance { get; }
    /// <summary>SocialPlan 资源。</summary>
    public CompensationSocialPlanResource SocialPlan { get; }

public sealed class CompensationArchiveResource
{
    private readonly RequestPipeline _pipeline;

    internal CompensationArchiveResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>创建薪资档案（POST /open-apis/compensation/v1/archives）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/compensation/v1/archives",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>批量查询员工薪资档案（POST /open-apis/compensation/v1/archives/query）。</summary>
    public Task<FeishuDataResponse> QueryAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/compensation/v1/archives/query",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CompensationChangeReasonResource
{
    private readonly RequestPipeline _pipeline;

    internal CompensationChangeReasonResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>批量查询定调薪原因（GET /open-apis/compensation/v1/change_reasons）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/compensation/v1/change_reasons",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CompensationIndicatorResource
{
    private readonly RequestPipeline _pipeline;

    internal CompensationIndicatorResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>批量查询薪资统计指标（GET /open-apis/compensation/v1/indicators）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/compensation/v1/indicators",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CompensationItemResource
{
    private readonly RequestPipeline _pipeline;

    internal CompensationItemResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>批量查询薪资项（GET /open-apis/compensation/v1/items）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/compensation/v1/items",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CompensationItemCategoryResource
{
    private readonly RequestPipeline _pipeline;

    internal CompensationItemCategoryResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>批量获取薪资项分类（GET /open-apis/compensation/v1/item_categories）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/compensation/v1/item_categories",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CompensationLumpSumPaymentResource
{
    private readonly RequestPipeline _pipeline;

    internal CompensationLumpSumPaymentResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>批量创建一次性支付记录（POST /open-apis/compensation/v1/lump_sum_payment/batch_create）。</summary>
    public Task<FeishuDataResponse> BatchCreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/compensation/v1/lump_sum_payment/batch_create",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>批量更正一次性支付记录（POST /open-apis/compensation/v1/lump_sum_payment/batch_update）。</summary>
    public Task<FeishuDataResponse> BatchUpdateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/compensation/v1/lump_sum_payment/batch_update",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>批量删除一次性支付记录（POST /open-apis/compensation/v1/lump_sum_payment/batch_remove）。</summary>
    public Task<FeishuDataResponse> BatchRemoveAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/compensation/v1/lump_sum_payment/batch_remove",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>查询一次性支付授予记录（POST /open-apis/compensation/v1/lump_sum_payment/query）。</summary>
    public Task<FeishuDataResponse> QueryAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/compensation/v1/lump_sum_payment/query",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>查询一次性授予明细（POST /open-apis/compensation/v1/lump_sum_payment/query_detail）。</summary>
    public Task<FeishuDataResponse> QueryDetailAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/compensation/v1/lump_sum_payment/query_detail",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CompensationPlanResource
{
    private readonly RequestPipeline _pipeline;

    internal CompensationPlanResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>批量查询薪资方案（GET /open-apis/compensation/v1/plans）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/compensation/v1/plans",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CompensationRecurringPaymentResource
{
    private readonly RequestPipeline _pipeline;

    internal CompensationRecurringPaymentResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>批量创建经常性支付记录（POST /open-apis/compensation/v1/recurring_payment/batch_create）。</summary>
    public Task<FeishuDataResponse> BatchCreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/compensation/v1/recurring_payment/batch_create",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>批量更正经常性支付记录（POST /open-apis/compensation/v1/recurring_payment/batch_update）。</summary>
    public Task<FeishuDataResponse> BatchUpdateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/compensation/v1/recurring_payment/batch_update",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>批量删除经常性支付记录（POST /open-apis/compensation/v1/recurring_payment/batch_remove）。</summary>
    public Task<FeishuDataResponse> BatchRemoveAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/compensation/v1/recurring_payment/batch_remove",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>查询经常性支付记录（POST /open-apis/compensation/v1/recurring_payment/query）。</summary>
    public Task<FeishuDataResponse> QueryAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/compensation/v1/recurring_payment/query",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CompensationSocialArchiveResource
{
    private readonly RequestPipeline _pipeline;

    internal CompensationSocialArchiveResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>批量获取员工参保档案（POST /open-apis/compensation/v1/social_archive/query）。</summary>
    public Task<FeishuDataResponse> QueryAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/compensation/v1/social_archive/query",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CompensationSocialArchiveAdjustRecordResource
{
    private readonly RequestPipeline _pipeline;

    internal CompensationSocialArchiveAdjustRecordResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>批量获取社保增减员记录（POST /open-apis/compensation/v1/social_archive_adjust_record/query）。</summary>
    public Task<FeishuDataResponse> QueryAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/compensation/v1/social_archive_adjust_record/query",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CompensationSocialInsuranceResource
{
    private readonly RequestPipeline _pipeline;

    internal CompensationSocialInsuranceResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>获取险种配置列表（GET /open-apis/compensation/v1/social_insurances）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/compensation/v1/social_insurances",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CompensationSocialPlanResource
{
    private readonly RequestPipeline _pipeline;

    internal CompensationSocialPlanResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>分页查询参保方案（GET /open-apis/compensation/v1/social_plans）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/compensation/v1/social_plans",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>按方案ID与生效日期查参保方案（POST /open-apis/compensation/v1/social_plans/query）。</summary>
    public Task<FeishuDataResponse> QueryAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/compensation/v1/social_plans/query",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

}
