// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.SecurityAndCompliance;

/// <summary>安全合规（security_and_compliance/v2 设备管理）（生成代码：7 个端点）。</summary>
public sealed class SecurityAndComplianceService
{
    private readonly RequestPipeline _pipeline;

    internal SecurityAndComplianceService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        DeviceApplyRecord = new SecurityAndComplianceDeviceApplyRecordResource(pipeline);
        DeviceRecord = new SecurityAndComplianceDeviceRecordResource(pipeline);
    }

    /// <summary>DeviceApplyRecord 资源。</summary>
    public SecurityAndComplianceDeviceApplyRecordResource DeviceApplyRecord { get; }
    /// <summary>DeviceRecord 资源。</summary>
    public SecurityAndComplianceDeviceRecordResource DeviceRecord { get; }

public sealed class SecurityAndComplianceDeviceApplyRecordResource
{
    private readonly RequestPipeline _pipeline;

    internal SecurityAndComplianceDeviceApplyRecordResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>审批设备申报（PUT /open-apis/security_and_compliance/v2/device_apply_records/:device_apply_record_id）。</summary>
    public Task<FeishuDataResponse> UpdateAsync(string deviceapplyrecordid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Put,
            Path = "/open-apis/security_and_compliance/v2/device_apply_records/:device_apply_record_id",
            PathParams =
            {
                ["device_apply_record_id"] = deviceapplyrecordid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class SecurityAndComplianceDeviceRecordResource
{
    private readonly RequestPipeline _pipeline;

    internal SecurityAndComplianceDeviceRecordResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>新增设备（POST /open-apis/security_and_compliance/v2/device_records）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/security_and_compliance/v2/device_records",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>分页查询设备列表（GET /open-apis/security_and_compliance/v2/device_records）。</summary>
    public Task<FeishuDataResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/security_and_compliance/v2/device_records",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取设备信息（GET /open-apis/security_and_compliance/v2/device_records/:device_record_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string devicerecordid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/security_and_compliance/v2/device_records/:device_record_id",
            PathParams =
            {
                ["device_record_id"] = devicerecordid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>更新设备（PUT /open-apis/security_and_compliance/v2/device_records/:device_record_id）。</summary>
    public Task<FeishuDataResponse> UpdateAsync(string devicerecordid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Put,
            Path = "/open-apis/security_and_compliance/v2/device_records/:device_record_id",
            PathParams =
            {
                ["device_record_id"] = devicerecordid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>删除设备（DELETE /open-apis/security_and_compliance/v2/device_records/:device_record_id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string devicerecordid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/security_and_compliance/v2/device_records/:device_record_id",
            PathParams =
            {
                ["device_record_id"] = devicerecordid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取设备认证信息（GET /open-apis/security_and_compliance/v2/device_records/mine）。</summary>
    public Task<FeishuDataResponse> MineAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/security_and_compliance/v2/device_records/mine",
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

}
