// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.Moments;

/// <summary>朋友圈（moments/v1）（生成代码：1 个端点）。</summary>
public sealed class MomentsService
{
    private readonly RequestPipeline _pipeline;

    internal MomentsService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        Post = new MomentsPostResource(pipeline);
    }

    /// <summary>Post 资源。</summary>
    public MomentsPostResource Post { get; }

public sealed class MomentsPostResource
{
    private readonly RequestPipeline _pipeline;

    internal MomentsPostResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>查询帖子信息（GET /open-apis/moments/v1/posts/:post_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string postid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/moments/v1/posts/:post_id",
            PathParams =
            {
                ["post_id"] = postid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

}
