// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.Sheets;

/// <summary>电子表格（sheets/v3 高频端点）（生成代码：3 个端点）。</summary>
public sealed class SheetsService
{
    private readonly RequestPipeline _pipeline;

    internal SheetsService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        Spreadsheet = new SheetsSpreadsheetResource(pipeline);
    }

    /// <summary>Spreadsheet 资源。</summary>
    public SheetsSpreadsheetResource Spreadsheet { get; }

public sealed class SheetsSpreadsheetResource
{
    private readonly RequestPipeline _pipeline;

    internal SheetsSpreadsheetResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>新建电子表格（POST /open-apis/sheets/v3/spreadsheets）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/sheets/v3/spreadsheets",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取电子表格信息（GET /open-apis/sheets/v3/spreadsheets/:spreadsheet_token）。</summary>
    public Task<FeishuDataResponse> GetAsync(string spreadsheettoken, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/sheets/v3/spreadsheets/:spreadsheet_token",
            PathParams =
            {
                ["spreadsheet_token"] = spreadsheettoken,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>更新电子表格（PATCH /open-apis/sheets/v3/spreadsheets/:spreadsheet_token）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string spreadsheettoken, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/sheets/v3/spreadsheets/:spreadsheet_token",
            PathParams =
            {
                ["spreadsheet_token"] = spreadsheettoken,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

}
