// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.Cardkit;

/// <summary>卡片实体（cardkit/v1，卡片 JSON 2.0）（生成代码：10 个端点）。</summary>
public sealed class CardkitService
{
    private readonly RequestPipeline _pipeline;

    internal CardkitService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        Card = new CardkitCardResource(pipeline);
        CardElement = new CardkitCardElementResource(pipeline);
    }

    /// <summary>Card 资源。</summary>
    public CardkitCardResource Card { get; }
    /// <summary>CardElement 资源。</summary>
    public CardkitCardElementResource CardElement { get; }

public sealed class CardkitCardResource
{
    private readonly RequestPipeline _pipeline;

    internal CardkitCardResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>创建卡片实体（POST /open-apis/cardkit/v1/cards）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/cardkit/v1/cards",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>局部更新卡片实体（POST /open-apis/cardkit/v1/cards/:card_id/batch_update）。</summary>
    public Task<FeishuDataResponse> BatchUpdateAsync(string cardid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/cardkit/v1/cards/:card_id/batch_update",
            PathParams =
            {
                ["card_id"] = cardid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>消息 ID 转卡片实体 ID（POST /open-apis/cardkit/v1/cards/id_convert）。</summary>
    public Task<FeishuDataResponse> IdConvertAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/cardkit/v1/cards/id_convert",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>更新卡片配置（PATCH /open-apis/cardkit/v1/cards/:card_id/settings）。</summary>
    public Task<FeishuDataResponse> SettingsAsync(string cardid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/cardkit/v1/cards/:card_id/settings",
            PathParams =
            {
                ["card_id"] = cardid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>全量更新卡片实体（PUT /open-apis/cardkit/v1/cards/:card_id）。</summary>
    public Task<FeishuDataResponse> UpdateAsync(string cardid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Put,
            Path = "/open-apis/cardkit/v1/cards/:card_id",
            PathParams =
            {
                ["card_id"] = cardid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class CardkitCardElementResource
{
    private readonly RequestPipeline _pipeline;

    internal CardkitCardElementResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>新增卡片组件（POST /open-apis/cardkit/v1/cards/:card_id/elements）。</summary>
    public Task<FeishuDataResponse> CreateAsync(string cardid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/cardkit/v1/cards/:card_id/elements",
            PathParams =
            {
                ["card_id"] = cardid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>流式更新文本（打字机效果）（PUT /open-apis/cardkit/v1/cards/:card_id/elements/:element_id/content）。</summary>
    public Task<FeishuDataResponse> ContentAsync(string cardid, string elementid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Put,
            Path = "/open-apis/cardkit/v1/cards/:card_id/elements/:element_id/content",
            PathParams =
            {
                ["card_id"] = cardid,
                ["element_id"] = elementid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>更新卡片组件（PUT /open-apis/cardkit/v1/cards/:card_id/elements/:element_id）。</summary>
    public Task<FeishuDataResponse> UpdateAsync(string cardid, string elementid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Put,
            Path = "/open-apis/cardkit/v1/cards/:card_id/elements/:element_id",
            PathParams =
            {
                ["card_id"] = cardid,
                ["element_id"] = elementid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>更新组件属性（PATCH /open-apis/cardkit/v1/cards/:card_id/elements/:element_id）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string cardid, string elementid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/cardkit/v1/cards/:card_id/elements/:element_id",
            PathParams =
            {
                ["card_id"] = cardid,
                ["element_id"] = elementid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>删除卡片组件（DELETE /open-apis/cardkit/v1/cards/:card_id/elements/:element_id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string cardid, string elementid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/cardkit/v1/cards/:card_id/elements/:element_id",
            PathParams =
            {
                ["card_id"] = cardid,
                ["element_id"] = elementid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

}
