// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.Mail;

/// <summary>邮箱（mail/v1 公共邮箱）（生成代码：4 个端点）。</summary>
public sealed class MailService
{
    private readonly RequestPipeline _pipeline;

    internal MailService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        PublicMailbox = new MailPublicMailboxResource(pipeline);
        MailboxGroup = new MailMailboxGroupResource(pipeline);
    }

    /// <summary>PublicMailbox 资源。</summary>
    public MailPublicMailboxResource PublicMailbox { get; }
    /// <summary>MailboxGroup 资源。</summary>
    public MailMailboxGroupResource MailboxGroup { get; }

public sealed class MailPublicMailboxResource
{
    private readonly RequestPipeline _pipeline;

    internal MailPublicMailboxResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>创建公共邮箱（POST /open-apis/mail/v1/public_mailboxes）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/mail/v1/public_mailboxes",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取公共邮箱列表（分页）（GET /open-apis/mail/v1/public_mailboxes）。</summary>
    public Task<FeishuDataResponse> ListAsync(IDictionary<string, string>? query = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/mail/v1/public_mailboxes",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取公共邮箱列表（分页）：自动翻页枚举 data.items。</summary>
    public async IAsyncEnumerable<System.Text.Json.JsonElement> ListAsyncEnumerate(IDictionary<string, string>? query = null, RequestOptions? options = null, int? limit = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var emitted = 0;
        string? pageToken = null;
        do
        {
            var pageQuery = query == null ? new Dictionary<string, string>() : new Dictionary<string, string>(query);
            if (pageToken != null) pageQuery["page_token"] = pageToken;
            var page = await ListAsync(pageQuery, options, cancellationToken);
            page.EnsureSuccess();
            if (page.Data is not { ValueKind: System.Text.Json.JsonValueKind.Object } data) yield break;
            if (!data.TryGetProperty("items", out var items) || items.ValueKind != System.Text.Json.JsonValueKind.Array) yield break;
            foreach (var item in items.EnumerateArray())
            {
                if (limit.HasValue && emitted >= limit.Value) yield break;
                emitted++;
                yield return item;
            }
            pageToken = page.PageToken is { Length: > 0 } ? page.PageToken : null;
        } while (pageToken != null);
    }

}

public sealed class MailMailboxGroupResource
{
    private readonly RequestPipeline _pipeline;

    internal MailMailboxGroupResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>创建邮箱组（POST /open-apis/mail/v1/mailbox_groups）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/mail/v1/mailbox_groups",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取邮箱组列表（分页）（GET /open-apis/mail/v1/mailbox_groups）。</summary>
    public Task<FeishuDataResponse> ListAsync(IDictionary<string, string>? query = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/mail/v1/mailbox_groups",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取邮箱组列表（分页）：自动翻页枚举 data.items。</summary>
    public async IAsyncEnumerable<System.Text.Json.JsonElement> ListAsyncEnumerate(IDictionary<string, string>? query = null, RequestOptions? options = null, int? limit = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var emitted = 0;
        string? pageToken = null;
        do
        {
            var pageQuery = query == null ? new Dictionary<string, string>() : new Dictionary<string, string>(query);
            if (pageToken != null) pageQuery["page_token"] = pageToken;
            var page = await ListAsync(pageQuery, options, cancellationToken);
            page.EnsureSuccess();
            if (page.Data is not { ValueKind: System.Text.Json.JsonValueKind.Object } data) yield break;
            if (!data.TryGetProperty("items", out var items) || items.ValueKind != System.Text.Json.JsonValueKind.Array) yield break;
            foreach (var item in items.EnumerateArray())
            {
                if (limit.HasValue && emitted >= limit.Value) yield break;
                emitted++;
                yield return item;
            }
            pageToken = page.PageToken is { Length: > 0 } ? page.PageToken : null;
        } while (pageToken != null);
    }

}

}
