// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.DocumentAi;

/// <summary>文档 AI 识别（document_ai/v1，18 类证照/票据识别）（生成代码：18 个端点）。</summary>
public sealed class DocumentAiService
{
    private readonly RequestPipeline _pipeline;

    internal DocumentAiService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        BankCard = new DocumentAiBankCardResource(pipeline);
        BusinessCard = new DocumentAiBusinessCardResource(pipeline);
        BusinessLicense = new DocumentAiBusinessLicenseResource(pipeline);
        ChinesePassport = new DocumentAiChinesePassportResource(pipeline);
        Contract = new DocumentAiContractResource(pipeline);
        DrivingLicense = new DocumentAiDrivingLicenseResource(pipeline);
        FoodManageLicense = new DocumentAiFoodManageLicenseResource(pipeline);
        FoodProduceLicense = new DocumentAiFoodProduceLicenseResource(pipeline);
        HealthCertificate = new DocumentAiHealthCertificateResource(pipeline);
        HkmMainlandTravelPermit = new DocumentAiHkmMainlandTravelPermitResource(pipeline);
        IdCard = new DocumentAiIdCardResource(pipeline);
        Resume = new DocumentAiResumeResource(pipeline);
        TaxiInvoice = new DocumentAiTaxiInvoiceResource(pipeline);
        TrainInvoice = new DocumentAiTrainInvoiceResource(pipeline);
        TwMainlandTravelPermit = new DocumentAiTwMainlandTravelPermitResource(pipeline);
        VatInvoice = new DocumentAiVatInvoiceResource(pipeline);
        VehicleInvoice = new DocumentAiVehicleInvoiceResource(pipeline);
        VehicleLicense = new DocumentAiVehicleLicenseResource(pipeline);
    }

    /// <summary>BankCard 资源。</summary>
    public DocumentAiBankCardResource BankCard { get; }
    /// <summary>BusinessCard 资源。</summary>
    public DocumentAiBusinessCardResource BusinessCard { get; }
    /// <summary>BusinessLicense 资源。</summary>
    public DocumentAiBusinessLicenseResource BusinessLicense { get; }
    /// <summary>ChinesePassport 资源。</summary>
    public DocumentAiChinesePassportResource ChinesePassport { get; }
    /// <summary>Contract 资源。</summary>
    public DocumentAiContractResource Contract { get; }
    /// <summary>DrivingLicense 资源。</summary>
    public DocumentAiDrivingLicenseResource DrivingLicense { get; }
    /// <summary>FoodManageLicense 资源。</summary>
    public DocumentAiFoodManageLicenseResource FoodManageLicense { get; }
    /// <summary>FoodProduceLicense 资源。</summary>
    public DocumentAiFoodProduceLicenseResource FoodProduceLicense { get; }
    /// <summary>HealthCertificate 资源。</summary>
    public DocumentAiHealthCertificateResource HealthCertificate { get; }
    /// <summary>HkmMainlandTravelPermit 资源。</summary>
    public DocumentAiHkmMainlandTravelPermitResource HkmMainlandTravelPermit { get; }
    /// <summary>IdCard 资源。</summary>
    public DocumentAiIdCardResource IdCard { get; }
    /// <summary>Resume 资源。</summary>
    public DocumentAiResumeResource Resume { get; }
    /// <summary>TaxiInvoice 资源。</summary>
    public DocumentAiTaxiInvoiceResource TaxiInvoice { get; }
    /// <summary>TrainInvoice 资源。</summary>
    public DocumentAiTrainInvoiceResource TrainInvoice { get; }
    /// <summary>TwMainlandTravelPermit 资源。</summary>
    public DocumentAiTwMainlandTravelPermitResource TwMainlandTravelPermit { get; }
    /// <summary>VatInvoice 资源。</summary>
    public DocumentAiVatInvoiceResource VatInvoice { get; }
    /// <summary>VehicleInvoice 资源。</summary>
    public DocumentAiVehicleInvoiceResource VehicleInvoice { get; }
    /// <summary>VehicleLicense 资源。</summary>
    public DocumentAiVehicleLicenseResource VehicleLicense { get; }

public sealed class DocumentAiBankCardResource
{
    private readonly RequestPipeline _pipeline;

    internal DocumentAiBankCardResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>识别文件中的银行卡（POST /open-apis/document_ai/v1/bank_card/recognize）。</summary>
    public Task<FeishuDataResponse> RecognizeBankCardAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/document_ai/v1/bank_card/recognize",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class DocumentAiBusinessCardResource
{
    private readonly RequestPipeline _pipeline;

    internal DocumentAiBusinessCardResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>识别文件中的名片（POST /open-apis/document_ai/v1/business_card/recognize）。</summary>
    public Task<FeishuDataResponse> RecognizeBusinessCardAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/document_ai/v1/business_card/recognize",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class DocumentAiBusinessLicenseResource
{
    private readonly RequestPipeline _pipeline;

    internal DocumentAiBusinessLicenseResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>识别文件中的营业执照（POST /open-apis/document_ai/v1/business_license/recognize）。</summary>
    public Task<FeishuDataResponse> RecognizeBusinessLicenseAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/document_ai/v1/business_license/recognize",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class DocumentAiChinesePassportResource
{
    private readonly RequestPipeline _pipeline;

    internal DocumentAiChinesePassportResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>识别文件中的中国护照（POST /open-apis/document_ai/v1/chinese_passport/recognize）。</summary>
    public Task<FeishuDataResponse> RecognizeChinesePassportAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/document_ai/v1/chinese_passport/recognize",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class DocumentAiContractResource
{
    private readonly RequestPipeline _pipeline;

    internal DocumentAiContractResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>提取文件中的合同字段（POST /open-apis/document_ai/v1/contract/field_extraction）。</summary>
    public Task<FeishuDataResponse> FieldExtractionAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/document_ai/v1/contract/field_extraction",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class DocumentAiDrivingLicenseResource
{
    private readonly RequestPipeline _pipeline;

    internal DocumentAiDrivingLicenseResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>识别文件中的驾驶证（POST /open-apis/document_ai/v1/driving_license/recognize）。</summary>
    public Task<FeishuDataResponse> RecognizeDrivingLicenseAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/document_ai/v1/driving_license/recognize",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class DocumentAiFoodManageLicenseResource
{
    private readonly RequestPipeline _pipeline;

    internal DocumentAiFoodManageLicenseResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>识别文件中的食品经营许可证（POST /open-apis/document_ai/v1/food_manage_license/recognize）。</summary>
    public Task<FeishuDataResponse> RecognizeFoodManageLicenseAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/document_ai/v1/food_manage_license/recognize",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class DocumentAiFoodProduceLicenseResource
{
    private readonly RequestPipeline _pipeline;

    internal DocumentAiFoodProduceLicenseResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>识别文件中的食品生产许可证（POST /open-apis/document_ai/v1/food_produce_license/recognize）。</summary>
    public Task<FeishuDataResponse> RecognizeFoodProduceLicenseAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/document_ai/v1/food_produce_license/recognize",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class DocumentAiHealthCertificateResource
{
    private readonly RequestPipeline _pipeline;

    internal DocumentAiHealthCertificateResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>识别文件中的健康证（POST /open-apis/document_ai/v1/health_certificate/recognize）。</summary>
    public Task<FeishuDataResponse> RecognizeHealthCertificateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/document_ai/v1/health_certificate/recognize",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class DocumentAiHkmMainlandTravelPermitResource
{
    private readonly RequestPipeline _pipeline;

    internal DocumentAiHkmMainlandTravelPermitResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>识别文件中的港澳居民来往内地通行证（POST /open-apis/document_ai/v1/hkm_mainland_travel_permit/recognize）。</summary>
    public Task<FeishuDataResponse> RecognizeHkmMainlandTravelPermitAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/document_ai/v1/hkm_mainland_travel_permit/recognize",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class DocumentAiIdCardResource
{
    private readonly RequestPipeline _pipeline;

    internal DocumentAiIdCardResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>识别文件中的身份证（POST /open-apis/document_ai/v1/id_card/recognize）。</summary>
    public Task<FeishuDataResponse> RecognizeIdCardAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/document_ai/v1/id_card/recognize",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class DocumentAiResumeResource
{
    private readonly RequestPipeline _pipeline;

    internal DocumentAiResumeResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>识别文件中的简历信息（POST /open-apis/document_ai/v1/resume/parse）。</summary>
    public Task<FeishuDataResponse> ParseAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/document_ai/v1/resume/parse",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class DocumentAiTaxiInvoiceResource
{
    private readonly RequestPipeline _pipeline;

    internal DocumentAiTaxiInvoiceResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>识别文件中的出租车发票（POST /open-apis/document_ai/v1/taxi_invoice/recognize）。</summary>
    public Task<FeishuDataResponse> RecognizeTaxiInvoiceAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/document_ai/v1/taxi_invoice/recognize",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class DocumentAiTrainInvoiceResource
{
    private readonly RequestPipeline _pipeline;

    internal DocumentAiTrainInvoiceResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>识别文件中的火车票（POST /open-apis/document_ai/v1/train_invoice/recognize）。</summary>
    public Task<FeishuDataResponse> RecognizeTrainInvoiceAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/document_ai/v1/train_invoice/recognize",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class DocumentAiTwMainlandTravelPermitResource
{
    private readonly RequestPipeline _pipeline;

    internal DocumentAiTwMainlandTravelPermitResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>识别文件中的台湾居民来往大陆通行证（POST /open-apis/document_ai/v1/tw_mainland_travel_permit/recognize）。</summary>
    public Task<FeishuDataResponse> RecognizeTwMainlandTravelPermitAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/document_ai/v1/tw_mainland_travel_permit/recognize",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class DocumentAiVatInvoiceResource
{
    private readonly RequestPipeline _pipeline;

    internal DocumentAiVatInvoiceResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>识别文件中的增值税发票（POST /open-apis/document_ai/v1/vat_invoice/recognize）。</summary>
    public Task<FeishuDataResponse> RecognizeVatInvoiceAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/document_ai/v1/vat_invoice/recognize",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class DocumentAiVehicleInvoiceResource
{
    private readonly RequestPipeline _pipeline;

    internal DocumentAiVehicleInvoiceResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>识别文件中的机动车发票（POST /open-apis/document_ai/v1/vehicle_invoice/recognize）。</summary>
    public Task<FeishuDataResponse> RecognizeVehicleInvoiceAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/document_ai/v1/vehicle_invoice/recognize",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class DocumentAiVehicleLicenseResource
{
    private readonly RequestPipeline _pipeline;

    internal DocumentAiVehicleLicenseResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>识别文件中的行驶证（POST /open-apis/document_ai/v1/vehicle_license/recognize）。</summary>
    public Task<FeishuDataResponse> RecognizeVehicleLicenseAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/document_ai/v1/vehicle_license/recognize",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

}
