// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.Drive;

/// <summary>云空间（drive/v1 文件与权限高频端点）（生成代码：10 个端点）。</summary>
public sealed class DriveService
{
    private readonly RequestPipeline _pipeline;

    internal DriveService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        File = new DriveFileResource(pipeline);
        Permission = new DrivePermissionResource(pipeline);
    }

    /// <summary>File 资源。</summary>
    public DriveFileResource File { get; }
    /// <summary>Permission 资源。</summary>
    public DrivePermissionResource Permission { get; }

public sealed class DriveFileResource
{
    private readonly RequestPipeline _pipeline;

    internal DriveFileResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>上传文件（分片全部一步）（POST /open-apis/drive/v1/files/upload_all）。</summary>
    public Task<FeishuDataResponse> UploadAllAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/drive/v1/files/upload_all",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>下载文件（GET /open-apis/drive/v1/files/:file_token/download）。</summary>
    public Task<ApiResponse> DownloadAsync(string filetoken, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/drive/v1/files/:file_token/download",
            PathParams =
            {
                ["file_token"] = filetoken,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        options = (options ?? RequestOptions.Default).WithFileDownload();
        return _pipeline.SendAsync(api, options, cancellationToken);
    }

    /// <summary>获取文件元数据（GET /open-apis/drive/v1/files/:file_token）。</summary>
    public Task<FeishuDataResponse> GetAsync(string filetoken, IDictionary<string, string>? query = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/drive/v1/files/:file_token",
            PathParams =
            {
                ["file_token"] = filetoken,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>创建文件夹（POST /open-apis/drive/v1/files/create_folder）。</summary>
    public Task<FeishuDataResponse> CreateFolderAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/drive/v1/files/create_folder",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>创建导入任务（POST /open-apis/drive/v1/import_tasks）。</summary>
    public Task<FeishuDataResponse> CreateImportTaskAsync(IDictionary<string, string>? query = null, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/drive/v1/import_tasks",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>创建导出任务（POST /open-apis/drive/v1/export_tasks）。</summary>
    public Task<FeishuDataResponse> CreateExportTaskAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/drive/v1/export_tasks",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>查询导入任务结果（GET /open-apis/drive/v1/import_tasks/:ticket）。</summary>
    public Task<FeishuDataResponse> GetImportTaskAsync(string ticket, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/drive/v1/import_tasks/:ticket",
            PathParams =
            {
                ["ticket"] = ticket,
            },
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>查询导出任务结果（GET /open-apis/drive/v1/export_tasks/:ticket）。</summary>
    public Task<FeishuDataResponse> GetExportTaskAsync(string ticket, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/drive/v1/export_tasks/:ticket",
            PathParams =
            {
                ["ticket"] = ticket,
            },
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class DrivePermissionResource
{
    private readonly RequestPipeline _pipeline;

    internal DrivePermissionResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>添加协作者权限（POST /open-apis/drive/v1/permissions/:token/members/create）。</summary>
    public Task<FeishuDataResponse> CreateMemberAsync(string token, IDictionary<string, string>? query = null, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/drive/v1/permissions/:token/members/create",
            PathParams =
            {
                ["token"] = token,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>设置云文档公开权限（PUT /open-apis/drive/v1/permissions/:token/public）。</summary>
    public Task<FeishuDataResponse> UpdatePublicAsync(string token, IDictionary<string, string>? query = null, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Put,
            Path = "/open-apis/drive/v1/permissions/:token/public",
            PathParams =
            {
                ["token"] = token,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

}
