// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.Base;

/// <summary>多维表格高级权限（base/v2 自定义角色）（生成代码：3 个端点）。</summary>
public sealed class BaseService
{
    private readonly RequestPipeline _pipeline;

    internal BaseService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        AppRole = new BaseAppRoleResource(pipeline);
    }

    /// <summary>AppRole 资源。</summary>
    public BaseAppRoleResource AppRole { get; }

public sealed class BaseAppRoleResource
{
    private readonly RequestPipeline _pipeline;

    internal BaseAppRoleResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>新增自定义角色（POST /open-apis/base/v2/apps/:app_token/roles）。</summary>
    public Task<FeishuDataResponse> CreateAsync(string apptoken, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/base/v2/apps/:app_token/roles",
            PathParams =
            {
                ["app_token"] = apptoken,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>列出自定义角色（GET /open-apis/base/v2/apps/:app_token/roles）。</summary>
    public Task<FeishuDataResponse> ListAsync(string apptoken, IDictionary<string, string>? query = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/base/v2/apps/:app_token/roles",
            PathParams =
            {
                ["app_token"] = apptoken,
            },
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>列出自定义角色：自动翻页枚举 data.items。</summary>
    public async IAsyncEnumerable<System.Text.Json.JsonElement> ListAsyncEnumerate(string apptoken, IDictionary<string, string>? query = null, RequestOptions? options = null, int? limit = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var emitted = 0;
        string? pageToken = null;
        do
        {
            var pageQuery = query == null ? new Dictionary<string, string>() : new Dictionary<string, string>(query);
            if (pageToken != null) pageQuery["page_token"] = pageToken;
            var page = await ListAsync(apptoken, pageQuery, options, cancellationToken);
            page.EnsureSuccess();
            if (page.Data is not { ValueKind: System.Text.Json.JsonValueKind.Object } data) yield break;
            if (!data.TryGetProperty("items", out var items) || items.ValueKind != System.Text.Json.JsonValueKind.Array) yield break;
            foreach (var item in items.EnumerateArray())
            {
                if (limit.HasValue && emitted >= limit.Value) yield break;
                emitted++;
                yield return item;
            }
            pageToken = page.PageToken is { Length: > 0 } ? page.PageToken : null;
        } while (pageToken != null);
    }

    /// <summary>更新自定义角色（PUT /open-apis/base/v2/apps/:app_token/roles/:role_id）。</summary>
    public Task<FeishuDataResponse> UpdateAsync(string apptoken, string roleid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Put,
            Path = "/open-apis/base/v2/apps/:app_token/roles/:role_id",
            PathParams =
            {
                ["app_token"] = apptoken,
                ["role_id"] = roleid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User, AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

}
