// FeishuSdk.CodeGen：从 apis.json 清单批量生成服务资源类（扩面 50+ 服务的生成器）。
// 生成目标：SendForAsync 管道调用 + FeishuDataResponse（原始 data）+ 可选分页枚举。
// 用法：dotnet run --project tools/FeishuSdk.CodeGen -- [apis.json 路径] [输出根目录]

using System.Text;
using System.Text.Json;

var manifestPath = args.Length > 0 ? args[0] : Path.Combine(AppContext.BaseDirectory, "apis.json");
var outputRoot = args.Length > 1
    ? args[1]
    : Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "src", "FeishuSdk", "Services"));

var manifest = JsonSerializer.Deserialize<Manifest>(
    await File.ReadAllTextAsync(manifestPath),
    new JsonSerializerOptions(JsonSerializerDefaults.Web) { PropertyNameCaseInsensitive = true })
    ?? throw new InvalidOperationException("bad manifest");

var generated = 0;
foreach (var service in manifest.Services)
{
    var dir = Path.Combine(outputRoot, service.Name);
    Directory.CreateDirectory(dir);
    var file = Path.Combine(dir, $"{service.Name}Service.g.cs");
    await File.WriteAllTextAsync(file, RenderService(service));
    generated++;
    Console.WriteLine($"generated: {file} ({service.Resources.Sum(r => r.Endpoints.Count)} endpoints)");
}
Console.WriteLine($"done: {generated} services, {manifest.Services.Sum(s => s.Resources.Sum(r => r.Endpoints.Count))} endpoints");

// ===================== 渲染（本地函数）=====================

static string RenderService(ServiceDef service)
{
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>");
    sb.AppendLine("#nullable enable");
    sb.AppendLine();
    sb.AppendLine("using System.Runtime.CompilerServices;");
    sb.AppendLine();
    sb.AppendLine($"namespace Feishu.Services.{service.Name};");
    sb.AppendLine();
    sb.AppendLine($"/// <summary>{Escape(service.Description)}（生成代码：{service.Resources.Sum(r => r.Endpoints.Count)} 个端点）。</summary>");
    sb.AppendLine($"public sealed class {service.Name}Service");
    sb.AppendLine("{");
    sb.AppendLine("    private readonly RequestPipeline _pipeline;");
    sb.AppendLine();
    sb.AppendLine($"    internal {service.Name}Service(RequestPipeline pipeline)");
    sb.AppendLine("    {");
    sb.AppendLine("        _pipeline = pipeline;");
    foreach (var resource in service.Resources)
        sb.AppendLine($"        {resource.Name} = new {service.Name}{resource.Name}Resource(pipeline);");
    sb.AppendLine("    }");
    sb.AppendLine();
    foreach (var resource in service.Resources)
    {
        sb.AppendLine($"    /// <summary>{Escape(resource.Name)} 资源。</summary>");
        sb.AppendLine($"    public {service.Name}{resource.Name}Resource {resource.Name} {{ get; }}");
    }
    sb.AppendLine();
    foreach (var resource in service.Resources)
        RenderResource(sb, service, resource);
    sb.AppendLine("}");
    return sb.ToString();
}

static void RenderResource(StringBuilder sb, ServiceDef service, ResourceDef resource)
{
    sb.AppendLine($"public sealed class {service.Name}{resource.Name}Resource");
    sb.AppendLine("{");
    sb.AppendLine("    private readonly RequestPipeline _pipeline;");
    sb.AppendLine();
    sb.AppendLine($"    internal {service.Name}{resource.Name}Resource(RequestPipeline pipeline) => _pipeline = pipeline;");
    sb.AppendLine();

    foreach (var ep in resource.Endpoints)
    {
        RenderEndpoint(sb, ep);
        if (ep.IsPagedList)
            RenderEnumerate(sb, ep);
    }

    sb.AppendLine("}");
    sb.AppendLine();
}

static void RenderEndpoint(StringBuilder sb, EndpointDef ep)
{
    var args = new List<string>();
    foreach (var p in ep.PathParams) args.Add($"string {ToCamel(p)}");
    if (ep.QueryParams.Count > 0)
        args.Add("IDictionary<string, string>? query = null");
    if (ep.HasBody || ep.IsMultipart) args.Add("object? body = null");
    args.Add("RequestOptions? options = null");
    args.Add("CancellationToken cancellationToken = default");
    var argList = string.Join(", ", args);

    var respType = ep.IsDownload ? "ApiResponse" : "FeishuDataResponse";
    sb.AppendLine($"    /// <summary>{Escape(ep.Description)}（{ep.HttpMethod} {ep.Path}）。</summary>");
    sb.AppendLine($"    public Task<{respType}> {ep.Method}({argList})");
    sb.AppendLine("    {");
    sb.AppendLine("        var api = new ApiRequest");
    sb.AppendLine("        {");
    sb.AppendLine($"            Method = HttpMethod.{NormalizeVerb(ep.HttpMethod)},");
    sb.AppendLine($"            Path = \"{ep.Path}\",");
    if (ep.PathParams.Count > 0)
    {
        sb.AppendLine("            PathParams =");
        sb.AppendLine("            {");
        foreach (var p in ep.PathParams)
            sb.AppendLine($"                [\"{p}\"] = {ToCamel(p)},");
        sb.AppendLine("            },");
    }
    if (ep.HasBody || ep.IsMultipart)
        sb.AppendLine("            Body = body,");
    sb.AppendLine("            SupportedTokenTypes = [" + string.Join(", ", ep.TokenTypes.Select(t => $"AccessTokenType.{t}")) + "],");
    sb.AppendLine("        };");
    if (ep.QueryParams.Count > 0)
    {
        sb.AppendLine("        if (query != null)");
        sb.AppendLine("            foreach (var kv in query)");
        sb.AppendLine("                api.QueryParams.Add(kv.Key, kv.Value);");
    }
    if (ep.IsDownload)
        sb.AppendLine("        options = (options ?? RequestOptions.Default).WithFileDownload();");
    if (ep.NeedHelpdeskAuth)
        sb.AppendLine("        options = (options ?? RequestOptions.Default).WithHelpdeskAuth();");
    var sendExpr = ep.IsDownload
        ? "_pipeline.SendAsync(api, options, cancellationToken);"
        : "_pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);";
    sb.AppendLine("        return " + sendExpr);
    sb.AppendLine("    }");
    sb.AppendLine();
}

static void RenderEnumerate(StringBuilder sb, EndpointDef ep)
{
    var pathArgs = string.Join(", ", ep.PathParams.Select(ToCamel));
    var typedPathArgs = string.Join(", ", ep.PathParams.Select(p => $"string {ToCamel(p)}"));
    var pathArgsWithComma = ep.PathParams.Count > 0 ? pathArgs + ", " : "";

    sb.AppendLine($"    /// <summary>{Escape(ep.Description)}：自动翻页枚举 data.items。</summary>");
    sb.AppendLine($"    public async IAsyncEnumerable<System.Text.Json.JsonElement> {ep.Method}Enumerate(" +
        (ep.PathParams.Count > 0 ? typedPathArgs + ", " : "") +
        (ep.QueryParams.Count > 0 ? "IDictionary<string, string>? query = null, " : "") +
        "RequestOptions? options = null, int? limit = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)");
    sb.AppendLine("    {");
    sb.AppendLine("        var emitted = 0;");
    sb.AppendLine("        string? pageToken = null;");
    sb.AppendLine("        do");
    sb.AppendLine("        {");
    if (ep.QueryParams.Count > 0)
    {
        sb.AppendLine("            var pageQuery = query == null ? new Dictionary<string, string>() : new Dictionary<string, string>(query);");
        sb.AppendLine("            if (pageToken != null) pageQuery[\"page_token\"] = pageToken;");
        var bodyArg = ep.HasBody || ep.IsMultipart ? "null, " : "";
        sb.AppendLine($"            var page = await {ep.Method}({pathArgsWithComma}pageQuery, {bodyArg}options, cancellationToken);");
    }
    else
    {
        sb.AppendLine($"            var page = await {ep.Method}({pathArgsWithComma}options, cancellationToken);");
    }
    sb.AppendLine("            page.EnsureSuccess();");
    sb.AppendLine("            if (page.Data is not { ValueKind: System.Text.Json.JsonValueKind.Object } data) yield break;");
    sb.AppendLine("            if (!data.TryGetProperty(\"items\", out var items) || items.ValueKind != System.Text.Json.JsonValueKind.Array) yield break;");
    sb.AppendLine("            foreach (var item in items.EnumerateArray())");
    sb.AppendLine("            {");
    sb.AppendLine("                if (limit.HasValue && emitted >= limit.Value) yield break;");
    sb.AppendLine("                emitted++;");
    sb.AppendLine("                yield return item;");
    sb.AppendLine("            }");
    sb.AppendLine("            pageToken = page.PageToken is { Length: > 0 } ? page.PageToken : null;");
    sb.AppendLine("        } while (pageToken != null);");
    sb.AppendLine("    }");
    sb.AppendLine();
}

static string NormalizeVerb(string verb) =>
    verb.ToUpperInvariant() switch
    {
        "GET" => "Get",
        "POST" => "Post",
        "PUT" => "Put",
        "PATCH" => "Patch",
        "DELETE" => "Delete",
        _ => verb,
    };

static string ToCamel(string s)
{
    var name = s.Length == 0 ? s : char.ToLowerInvariant(s[0]) + s[1..].Replace("_", "");
    return CSharpKeywords.Reserved.Contains(name) ? "@" + name : name;
}

static string Escape(string s) => s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

// ===================== 模型 =====================

internal static class CSharpKeywords
{
    public static readonly HashSet<string> Reserved = new(StringComparer.Ordinal)
    {
        "namespace", "class", "struct", "enum", "interface", "event", "params", "ref", "out", "in",
        "base", "bool", "byte", "char", "decimal", "double", "float", "int", "long", "object",
        "operator", "short", "string", "this", "typeof", "void", "default", "lock", "new", "return",
        "switch", "case", "if", "else", "for", "foreach", "while", "do", "try", "catch", "finally",
        "throw", "using", "var", "null", "true", "false", "static", "public", "private", "internal",
    };
}

sealed class Manifest
{
    public List<ServiceDef> Services { get; set; } = new();
}

sealed class ServiceDef
{
    public string Name { get; set; } = "";
    public string Description { get; set; } = "";
    public List<ResourceDef> Resources { get; set; } = new();
}

sealed class ResourceDef
{
    public string Name { get; set; } = "";
    public List<EndpointDef> Endpoints { get; set; } = new();
}

sealed class EndpointDef
{
    public string Method { get; set; } = "";          // CreateAsync
    public string Description { get; set; } = "";
    public string HttpMethod { get; set; } = "POST";  // GET/POST/PUT/PATCH/DELETE
    public string Path { get; set; } = "";            // /open-apis/x/v1/y/:id
    public List<string> TokenTypes { get; set; } = new() { "Tenant" };
    public List<string> PathParams { get; set; } = new();
    public List<string> QueryParams { get; set; } = new();
    public bool HasBody { get; set; }
    public bool IsMultipart { get; set; }
    public bool IsDownload { get; set; }
    public bool IsPagedList { get; set; }             // data.items + page_token/has_more
    public bool NeedHelpdeskAuth { get; set; }        // 服务台鉴权头
}

