// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.Acs;

/// <summary>智能门禁（acs/v1）（生成代码：14 个端点）。</summary>
public sealed class AcsService
{
    private readonly RequestPipeline _pipeline;

    internal AcsService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        AccessRecord = new AcsAccessRecordResource(pipeline);
        Device = new AcsDeviceResource(pipeline);
        RuleExternal = new AcsRuleExternalResource(pipeline);
        User = new AcsUserResource(pipeline);
        UserFace = new AcsUserFaceResource(pipeline);
        Visitor = new AcsVisitorResource(pipeline);
    }

    /// <summary>AccessRecord 资源。</summary>
    public AcsAccessRecordResource AccessRecord { get; }
    /// <summary>Device 资源。</summary>
    public AcsDeviceResource Device { get; }
    /// <summary>RuleExternal 资源。</summary>
    public AcsRuleExternalResource RuleExternal { get; }
    /// <summary>User 资源。</summary>
    public AcsUserResource User { get; }
    /// <summary>UserFace 资源。</summary>
    public AcsUserFaceResource UserFace { get; }
    /// <summary>Visitor 资源。</summary>
    public AcsVisitorResource Visitor { get; }

public sealed class AcsAccessRecordResource
{
    private readonly RequestPipeline _pipeline;

    internal AcsAccessRecordResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>获取门禁记录列表（分页）（GET /open-apis/acs/v1/access_records）。</summary>
    public Task<FeishuDataResponse> ListAsync(IDictionary<string, string>? query = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/acs/v1/access_records",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取门禁记录列表（分页）：自动翻页枚举 data.items。</summary>
    public async IAsyncEnumerable<System.Text.Json.JsonElement> ListAsyncEnumerate(IDictionary<string, string>? query = null, RequestOptions? options = null, int? limit = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var emitted = 0;
        string? pageToken = null;
        do
        {
            var pageQuery = query == null ? new Dictionary<string, string>() : new Dictionary<string, string>(query);
            if (pageToken != null) pageQuery["page_token"] = pageToken;
            var page = await ListAsync(pageQuery, options, cancellationToken);
            page.EnsureSuccess();
            if (page.Data is not { ValueKind: System.Text.Json.JsonValueKind.Object } data) yield break;
            if (!data.TryGetProperty("items", out var items) || items.ValueKind != System.Text.Json.JsonValueKind.Array) yield break;
            foreach (var item in items.EnumerateArray())
            {
                if (limit.HasValue && emitted >= limit.Value) yield break;
                emitted++;
                yield return item;
            }
            pageToken = page.PageToken is { Length: > 0 } ? page.PageToken : null;
        } while (pageToken != null);
    }

    /// <summary>下载开门人脸抓拍图（GET /open-apis/acs/v1/access_records/:access_record_id/access_photo）。</summary>
    public Task<ApiResponse> GetAccessPhotoAsync(string accessrecordid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/acs/v1/access_records/:access_record_id/access_photo",
            PathParams =
            {
                ["access_record_id"] = accessrecordid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        options = (options ?? RequestOptions.Default).WithFileDownload();
        return _pipeline.SendAsync(api, options, cancellationToken);
    }

}

public sealed class AcsDeviceResource
{
    private readonly RequestPipeline _pipeline;

    internal AcsDeviceResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>获取门禁设备列表（GET /open-apis/acs/v1/devices）。</summary>
    public Task<FeishuDataResponse> ListAsync(IDictionary<string, string>? query = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/acs/v1/devices",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取门禁设备列表：自动翻页枚举 data.items。</summary>
    public async IAsyncEnumerable<System.Text.Json.JsonElement> ListAsyncEnumerate(IDictionary<string, string>? query = null, RequestOptions? options = null, int? limit = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var emitted = 0;
        string? pageToken = null;
        do
        {
            var pageQuery = query == null ? new Dictionary<string, string>() : new Dictionary<string, string>(query);
            if (pageToken != null) pageQuery["page_token"] = pageToken;
            var page = await ListAsync(pageQuery, options, cancellationToken);
            page.EnsureSuccess();
            if (page.Data is not { ValueKind: System.Text.Json.JsonValueKind.Object } data) yield break;
            if (!data.TryGetProperty("items", out var items) || items.ValueKind != System.Text.Json.JsonValueKind.Array) yield break;
            foreach (var item in items.EnumerateArray())
            {
                if (limit.HasValue && emitted >= limit.Value) yield break;
                emitted++;
                yield return item;
            }
            pageToken = page.PageToken is { Length: > 0 } ? page.PageToken : null;
        } while (pageToken != null);
    }

}

public sealed class AcsRuleExternalResource
{
    private readonly RequestPipeline _pipeline;

    internal AcsRuleExternalResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>创建或更新权限组（POST /open-apis/acs/v1/rule_external）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/acs/v1/rule_external",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取权限组信息（GET /open-apis/acs/v1/rule_external）。</summary>
    public Task<FeishuDataResponse> GetAsync(IDictionary<string, string>? query = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/acs/v1/rule_external",
            SupportedTokenTypes = [AccessTokenType.User],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>删除权限组（DELETE /open-apis/acs/v1/rule_external）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(IDictionary<string, string>? query = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/acs/v1/rule_external",
            SupportedTokenTypes = [AccessTokenType.User],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>设备绑定权限组（POST /open-apis/acs/v1/rule_external/device_bind）。</summary>
    public Task<FeishuDataResponse> DeviceBindAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/acs/v1/rule_external/device_bind",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class AcsUserResource
{
    private readonly RequestPipeline _pipeline;

    internal AcsUserResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>获取单个门禁用户（GET /open-apis/acs/v1/users/:user_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string userid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/acs/v1/users/:user_id",
            PathParams =
            {
                ["user_id"] = userid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取门禁用户列表（分页）（GET /open-apis/acs/v1/users）。</summary>
    public Task<FeishuDataResponse> ListAsync(IDictionary<string, string>? query = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/acs/v1/users",
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        if (query != null)
            foreach (var kv in query)
                api.QueryParams.Add(kv.Key, kv.Value);
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取门禁用户列表（分页）：自动翻页枚举 data.items。</summary>
    public async IAsyncEnumerable<System.Text.Json.JsonElement> ListAsyncEnumerate(IDictionary<string, string>? query = null, RequestOptions? options = null, int? limit = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var emitted = 0;
        string? pageToken = null;
        do
        {
            var pageQuery = query == null ? new Dictionary<string, string>() : new Dictionary<string, string>(query);
            if (pageToken != null) pageQuery["page_token"] = pageToken;
            var page = await ListAsync(pageQuery, options, cancellationToken);
            page.EnsureSuccess();
            if (page.Data is not { ValueKind: System.Text.Json.JsonValueKind.Object } data) yield break;
            if (!data.TryGetProperty("items", out var items) || items.ValueKind != System.Text.Json.JsonValueKind.Array) yield break;
            foreach (var item in items.EnumerateArray())
            {
                if (limit.HasValue && emitted >= limit.Value) yield break;
                emitted++;
                yield return item;
            }
            pageToken = page.PageToken is { Length: > 0 } ? page.PageToken : null;
        } while (pageToken != null);
    }

    /// <summary>修改用户部分信息（韦根卡号）（PATCH /open-apis/acs/v1/users/:user_id）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string userid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/acs/v1/users/:user_id",
            PathParams =
            {
                ["user_id"] = userid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class AcsUserFaceResource
{
    private readonly RequestPipeline _pipeline;

    internal AcsUserFaceResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>下载人脸图片（GET /open-apis/acs/v1/users/:user_id/face）。</summary>
    public Task<ApiResponse> GetAsync(string userid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/acs/v1/users/:user_id/face",
            PathParams =
            {
                ["user_id"] = userid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        options = (options ?? RequestOptions.Default).WithFileDownload();
        return _pipeline.SendAsync(api, options, cancellationToken);
    }

    /// <summary>上传人脸图片（PUT /open-apis/acs/v1/users/:user_id/face）。</summary>
    public Task<FeishuDataResponse> UpdateAsync(string userid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Put,
            Path = "/open-apis/acs/v1/users/:user_id/face",
            PathParams =
            {
                ["user_id"] = userid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

public sealed class AcsVisitorResource
{
    private readonly RequestPipeline _pipeline;

    internal AcsVisitorResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>添加访客（POST /open-apis/acs/v1/visitors）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/acs/v1/visitors",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>删除访客（DELETE /open-apis/acs/v1/visitors/:visitor_id）。</summary>
    public Task<FeishuDataResponse> DeleteAsync(string visitorid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Delete,
            Path = "/open-apis/acs/v1/visitors/:visitor_id",
            PathParams =
            {
                ["visitor_id"] = visitorid,
            },
            SupportedTokenTypes = [AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

}
