// <auto-generated> 由 FeishuSdk.CodeGen 从 apis.json 生成；协议走 RequestPipeline，与手写服务一致。</auto-generated>
#nullable enable

using System.Runtime.CompilerServices;

namespace Feishu.Services.Board;

/// <summary>白板（board/v1）（生成代码：3 个端点）。</summary>
public sealed class BoardService
{
    private readonly RequestPipeline _pipeline;

    internal BoardService(RequestPipeline pipeline)
    {
        _pipeline = pipeline;
        Whiteboard = new BoardWhiteboardResource(pipeline);
    }

    /// <summary>Whiteboard 资源。</summary>
    public BoardWhiteboardResource Whiteboard { get; }

public sealed class BoardWhiteboardResource
{
    private readonly RequestPipeline _pipeline;

    internal BoardWhiteboardResource(RequestPipeline pipeline) => _pipeline = pipeline;

    /// <summary>创建白板（POST /open-apis/board/v1/whiteboards）。</summary>
    public Task<FeishuDataResponse> CreateAsync(object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Post,
            Path = "/open-apis/board/v1/whiteboards",
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>获取白板信息（GET /open-apis/board/v1/whiteboards/:whiteboard_id）。</summary>
    public Task<FeishuDataResponse> GetAsync(string whiteboardid, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Get,
            Path = "/open-apis/board/v1/whiteboards/:whiteboard_id",
            PathParams =
            {
                ["whiteboard_id"] = whiteboardid,
            },
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

    /// <summary>修改白板标题（PATCH /open-apis/board/v1/whiteboards/:whiteboard_id）。</summary>
    public Task<FeishuDataResponse> PatchAsync(string whiteboardid, object? body = null, RequestOptions? options = null, CancellationToken cancellationToken = default)
    {
        var api = new ApiRequest
        {
            Method = HttpMethod.Patch,
            Path = "/open-apis/board/v1/whiteboards/:whiteboard_id",
            PathParams =
            {
                ["whiteboard_id"] = whiteboardid,
            },
            Body = body,
            SupportedTokenTypes = [AccessTokenType.Tenant, AccessTokenType.User],
        };
        return _pipeline.SendForAsync<FeishuDataResponse>(api, options, cancellationToken);
    }

}

}
